uktrade/lite-api

- organisations/models.py
- organisations/tests/tests_users.py
- organisations/urls.py
- organisations/views/users.py
- test_helpers/clients.py
- users/libraries/get_user.py
- users/serializers.py
On Users on exporter, can no longer deactivate them as the button is no longer there
Steps:
Go to exporter homepage
Click manage my organisation
Click Users
Click on a user other than yourself
Notice there is no deactivate button
Changes
Added endpoints for getting and putting an individual user on an organisation
Added tests for viewing an individual user, as well as updating their status (and preventing their status update too!)
> Bug: LT-1468 - Deactivate users

- applications/helpers.py
- applications/tests/tests_create.py
Fixes the validation on the first question asked in the application flow.
> fix: LT-1829 - Standard licence/open licence question now mandatory

- applications/libraries/licence.py
- cases/enums.py
- reason for this being MOD clearance applications (F680, Exhibition and Gifting) not having an export type, so no default licence duration was being returned when the advice was finalised
- added a check for whether the application type does not use an export type - assigning temporary duration if that's the case
_This is to unblock LT-1168._
Forms part of https://uktrade.atlassian.net/browse/LT-2200 
NOTE: this does not address the finalised advice not showing on the exporter's side bug
> bug: LT-2200 - Finalising MOD licence throws an API error

- cases/tests/tests_is_recently_updated.py
- conf/authentication.py
- conf/urls.py
- letter_templates/helpers.py
- organisations/tests/tests_users.py
- static/control_list_entries/parser.py
- static/management/SeedCommand.py
- static/management/commands/seedall.py
- static/management/commands/seedcountries.py
- test_helpers/clients.py
`from django.conf import settings` is not a file but a class making an abstraction of the concepts, default settings and your site-specific settings.
Django also does other checks when you use from django.conf import settings.
https://docs.djangoproject.com/en/2.2/topics/settings/#using-settings-in-python-code
> Replace direct settings import with django settings import

- licences/migrations/0011_map_goodonapplication_to_goodonlicence.py
Removing the `status=LicenceStatus.ISSUED`  from the filter so that draft licenced goods are also converted, otherwise the migration fails for draft licences (and we lose data on goods from draft licences)
> Fix goods on application data migration

- conf/settings.py
The dev environments are run with DEBUG=True but we don't install
django_extensions in those environments so the app fails to start.
This only activates django_extensions if it is installed
> Settings: Allow DEBUG=True if no django_extensions installed

- .coveragerc
- Pipfile
- Pipfile.lock
- api/letter_templates/custom_tags.py
- api/letter_templates/layouts/application_form.html
This commit removes the content for lite-internal and lite-exporter that has
been moved to lite-frontend.
This content is no longer maintained in `lite-content` so to avoid confusion it
has been removed.
Update:
lite-api still relies on lite_exporter_content so I've moved those strings to `lite_api/strings.py` to make sure it continues to work
> LTD-194: Update version of lite-content subrepo

- Pipfile
- Pipfile.lock
- api/letter_templates/helpers.py
- api/letter_templates/tests/tests_view.py
We are using markdown to render user content in bold, italic and underline but
markdown doesn't support underline so inline html is used in markdown.
The current code escaping html tags, marking it as safe to avoid escaping
underline html tags.
> Mark user text as safe to fix underlining

- api/conf/urls.py
The API returns a django 500 error page when there is a unhandled error, this
should be a json response instead so this commit tells djagno to use the DRF
provided Generic Error Views https://www.django-rest-framework.org/api-guide/exceptions/#generic-error-views
> Generic Error Views

- api/letter_templates/context_generator.py
- api/letter_templates/tests/tests_context_generation.py
This changes the way Document generation works so it looks at the firearm
details on the good on application instead of the good. This will continue to
work for older cases where there is no firearms detail on the GOA by falling
back to the good.
> LTD-411 Update Document Generation for FirearmDetails on Good on App

- api/goods/serializers.py
Firearms calibre and year of manufacture should error if provided but null,
this doesn't make them required and is just on the serializer so they can be
null if the model is created directly using the model.
corresponding lite-frontend PR: https://github.com/uktrade/lite-frontend/pull/91/files
> LTD-392 Make sure invalid/null validation works

- api/goods/serializers.py
- api/goods/tests/tests_edit.py
When we specify a firearm product is a replica then we need to provide
description. If we edit and change the status to not a replica then
description was not removed, this change resets this.
> Reset firearm replica description if the product is not a replica

- api/cases/generated_documents/helpers.py
- api/goods/tests/tests_edit.py
- api/letter_templates/helpers.py
- api/letter_templates/layouts/siel.html
The text in the licence template was hard coded and therefore wouldn't match the
"include_digital_signature" boolean set by the user when creating the template.
This change passes the value to the part where the template is generated so it
can be correctly displayed.
> LTD-319: Digital signature text in licence template mismatch

- api/external_data/documents.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
Currently we only filter out revoked denials on index create, but do not handle when denials have been revoked after tehy area already indexed.
> Exclude revoked denials already in ES

- api/goods/serializers.py
- api/goods/tests/tests_edit.py
When a partial update to a good is submitted, the serializer was clearing the
CLCs attached. This commit changes the serializer to not overwrite the CLCs on a
good if a partial update is received.
> LTD-507: CLC cleared when adding firearm certificate

- api/cases/models.py
- api/letter_templates/context_generator.py
- api/letter_templates/templates/letter_templates/ecju.html
- api/letter_templates/tests/tests_context_generation.py
There are 2 parts to this -
1. Include references in the letter 8a12422e90f9bdf09e8c06c8f3d53215b6f624a2
2. Include case officer's name in the letter 8a12422e90f9bdf09e8c06c8f3d53215b6f624a2
In order to do (2), I had to do some digging into the models.
After these changes, we should be able to generate the letter specified in the ticket using LITE.
P.S. I have changed the standard ECJU letter template. This should be ok for the references but I am not sure about the case officer's name. LMK if there are any issues with this.
> [LTD-699] SIEL cover letter

- api/cases/generated_documents/helpers.py
- api/cases/generated_documents/tests/test_generate_document.py
- api/core/helpers.py
- api/letter_templates/helpers.py
This bug resulted from a lack of exception handling and was exacerbated by the poor code that looked for `error` in a string. 
In that, if a user puts `error` in the form for customising the text, not only did the API incorrectly thought there was an error in generating the document but in trying to find that (nonexistent) error, ran into a real `KeyError`.
> LTD-745 API errors

- api/applications/models.py
- api/licences/serializers/hmrc_integration.py
Currently we use description in the licence line in edifact file sent to HMRC but it is made optional so it can be empty however
this is a mandatory field in the edifact file so use mandatory field "name" instead.
> LTD-776: Include good name in the data sent to lite-hmrc service

- api/users/tests/tests_create_exporter.py
- api/users/tests/tests_exporter_authentication.py
- api/users/views.py
If the user uses email in uppercase when registering an organisation then it
is saved as lower case when saving the BaseUser instance because of this we
fail to authenticate the user when logged in with the email in upper case.
Fix this by ignoring the case when looking for the exporter.
Add a test that ensures user can be authenticated by using email in uppercase.
> LTD-765: Ignore case when looking for ExporterUser using email

- Pipfile
- Pipfile.lock
- api/applications/libraries/document_helpers.py
- api/applications/tests/test_documents.py
- api/audit_trail/apps.py
- api/audit_trail/signals.py
- api/audit_trail/tests/factories.py
- api/audit_trail/tests/test_audit_trail.py
- api/audit_trail/tests/test_case_activity_filter.py
- api/conf/settings.py
- api/queries/goods_query/tests/test_goods_queries.py
- api/queries/goods_query/views.py
This does 3 things.
1) It adds `django-log-formatter-ecs`.
2) It adds a signal that emits Audit logs in ECS format.
3) Fixes a bunch of tests (and application logic) that was always broken but only got exposed because we started serializing all the `Audit` instances.
(2) looks like the following:
```
{
"asctime": "2021-04-26 14:37:40,970",
"levelname": "INFO",
"message": "ExporterUser object (f0aaf9d1-1bae-4681-b2e3-318da86e46c8) created_final_advice StandardApplication object (0bc97090-4152-42b2-93c6-1bf9d5eefa6f) 0 minutes ago",
"filename": "signals.py",
"lineno": 19,
"threadName": "MainThread",
"name": "api.audit_trail.signals",
"thread": 4626759168,
"created": 1619444260.970651,
"process": 33461,
"processName": "MainProcess",
"relativeCreated": 29715.826988220215,
"module": "signals", …
```
> Emit audit logs

- api/applications/helpers.py
- api/applications/tests/test_helpers.py
This PR does 2 things -
1. It removes addresses from the ES query for sanctions.
2. It removes the tests that were related to addresses.
It does not -
1. Remove the machinery that ingests addresses for sanctions and generate indices etc.
2. Fix the way tests are written - using weird class inheritance instead of pytest fixtures.
3. Strictly do what the spec says e.g. ATM "Jackson, Jeremy" and "Mr. Jeremy Jackson" will match "Jeremy Jackson". I think that (1) this is how it should be and (2) we can always do a second pass.
> [LTD-682] Remove address from the ES query & update tests.

- api/flags/views.py
- api/staticdata/management/commands/seedflags.py
Reverts some changes introduced in #786 and #785. There are a couple of reasons for this -
1) Most important one - we cannot `delete_unused_object` for `Flag` model. The reason is that, unlike other "seeded" models, the `Flag` model comprises seeded (system) flags as well as user-defined flags. In the same model 🤦 
(this was my bad, I should have realised this but didn't)
2) The second one is more insidious. The order in which filters are applied in `FlagsListCreateView.get_queryset` matters. As a result, this doesn't work e.g. if I have `name=UK` and `include_system_flags=True`. The results will include flags that have `UK` in the name as well as ALL the system flags.
> [LTD-1055] Revert changes

- api/data_workspace/application_views.py
This was [failing](https://data-flow-staging.london.cloudapps.digital/log?dag_id=LITEPartyOnApplicationPipeline&task_id=insert-into-temp-table-datasets_db&execution_date=2021-08-24T00%3A00%3A00%2B00%3A00) on the data-flow side. 
The working hypothesis was that the lack of order was causing some issues with pagination.
> Add order.

- api/compliance/tests/test_exporter_compliance_views.py
This is marked as failed temporarily as it is a random failure and it
does not affect SIEL licences.
> Mark compliance test as fail as it fails randomnly

- api/cases/tasks.py
- api/cases/tests/test_sla.py
If you read carefully, we are supposed to only stop the counter for `FINALISED`, `CLOSED`, `WITHDRAWN`.
I am going with `CaseStatusEnum.terminal_statuses()` because that seems like a more exhaustive list, which means it includes `FINALISED`, `CLOSED`, `WITHDRAWN` amongst others.
> [LTD-1028] Stop SLA for cases with terminal status.

- api/data_workspace/audit_views.py
- api/data_workspace/serializers.py
- api/data_workspace/tests/test_audit_views.py
- api/data_workspace/tests/test_serializers.py
- api/data_workspace/urls.py
- test_helpers/clients.py
This endpoint exposes 'move case' audit events in the following format:
```
{
"created_at": "2021-06-08T17:31:15.520183+01:00",
"user": "00000000-0000-0000-0000-000000000001",
"case": "b878c4f8-8f7c-45f9-ab06-143de04de3b5",
"queue": "4dfc0d0b-c0c0-4f59-897b-b7d596bed930"
},
```
> Create endpoint for retrieving move case audit events

- api/support/management/commands/mark_queries_as_resolved.py
This is useful to support activities where we may need to manually
set some of the ECJU queries as resolved. Please see command help
for more details
> LTD: Add management command to mark unresolved ECJU queries as resolved

- api/audit_trail/signals.py
- api/cases/tests/test_grant_licence.py
- api/cases/tests/test_view_advice.py
- api/licences/libraries/hmrc_integration_operations.py
- api/licences/models.py
- api/licences/tests/test_audit_licence.py
- api/organisations/tests/test_organisations.py
We need to expose licence status changes to Data Workspace so that reports can see them. Reports consider licence status changes as "incidents" and they're reported on individually.
This PR ensures auditing of licence status changes happens centrally via a pre_save signal - so that no licence status changes will escape audit.
> Audit licence status changes

- api/cases/tests/test_view_advice.py
- api/organisations/tests/test_organisations.py
- test_helpers/clients.py
- Stops seeding unit-tests when we use pytest's `--reuse-db`
- Fix timezone failing tests.
> Fix test-suite seed: don't seed when we use --reuse-db

- api/conftest.py
Loads all factories as `pytest.fixture` so they can be used directly without having to manually import
```
class TestTeam():
def test_my_team(team_factory):
my_team = team_factory()
```
NOTE: This will only work with pytest tests, you will still need to load manually the factories in existing vanilla Django tests.
> Autoload all factories to use directly in pytest tests

- api/licences/service.py
- api/licences/tests/test_service.py
Because description is optional and can be empty.
> LTD-1418: Display product name under licences tab instead of description

- api/goods/tests/factories.py
- api/letter_templates/context_generator.py
- api/letter_templates/tests/test_context_generation.py
- api/licences/serializers/hmrc_integration.py
- test_helpers/clients.py
The generated licence document (pdf) contains the list of products in the licence
that require a licence along with their name, quantity etc. Currently these
are being ordered using their description field. Because of this the order in
the licence doesn't match with the order in which they are added to the
application. This has serious implications wrt HMRC integration.
When the licence details are sent to HMRC we send the product details as per
the order they are entered in the application but when products are declared
at the customs they use the order defined in the licence. This can result in
differences in quantities and the customs system may reject the products.
Eg if the quantity shows up as higher than allowed in licence.
Fix this by removing the ordering by description and add a …
> LTD-1412: Fix products order in generated licence template

- Pipfile
- Pipfile.lock
There's already the below in `settings.py` so nothing more is needed than just adding the packages to Pipfile:
```
if DEBUG and "django_extensions" in sys.modules:
INSTALLED_APPS.append("django_extensions")
```
This also adds explicitly `importlib-metadata = "==4.8.1"` to solve a recurring issue with failing tests. This is in standard Python3.8 but since we still use 3.7 we need to [manually include it](https://pypi.org/project/importlib-metadata/) and there's sometimes a version mismatch in CircleCI which this solves.
> Enable django-extensions and ipython when DEBUG=True

- api/licences/helpers.py
- api/licences/tests/test_get_licences.py
Filter out any goods that are not controlled (NLR) before attempting to serialize the goods on a licence.
> Exclude NLR goods from serialization

- api/staticdata/management/commands/seeddenialreasons.py
This command will also remove any associated advice->denial reason
mappings via the many-to-many through table which is not desired.
> Don't delete unused denial reasons

- api/licences/serializers/view_licence.py
It's not required by the LITEGoodOnLicencesPipeline and causes issues with NLR products
> Don't serialize nested advice

- api/data_workspace/views.py
Ordering by name alone causes non-deterministic behaviour when multiple parties exist with the same name (which is common in production). This breaks pagination - because the same party can be emitted on different pages. That in turn breaks other things like unique constraints in Data Workspace.
> Additionally order by id so not to break pagination

- api/flags/serializers.py
id is used to determine if countersigning is required or not
> LTD-1594: Include Flag id in the serializer fields

- api/applications/serializers/advice.py
Users don't really submit recommendation for NLR type but to be able
to generate NLR letter we need final advice of NLR type hence make
the advice text optional in this case.
> LTD-1666: Advice text is optional for NLR

- api/search/signals.py
- api/search/tasks.py
- api/search/tests/test_signals.py
- api/search/tests/test_tasks.py
Changes to certain models trigger an Elastic Search index update on `save()`. If a model has a large number of related items (e.g. a case with many goods) then the ES update can significantly slow down the `save()` call and cause things to timeout.
This PR makes the ES index update asynchronous by moving the updates to a background task.
> LTD-1699: Use background task for ES index update

- api/audit_trail/payload.py
- api/audit_trail/tests/test_audit_payload.py
If a timeline message is changed it potentially no longer matches the payload parameters that are stored for historic audit records. This PR allows a default value to be supplied for parameters so the code has a fallback option.
Also improves error reporting.
> LTD-1676: Support default values for audit substitution params

- .bandit
- api/conftest.py
- api/staticdata/countries/migrations/0002_rename_countries.py
- api/staticdata/countries/test.py
This ticket change names from United Kingdom to Great Britain. Essentially it is what being asked in the story by adding Great Britain and removing United Kingdom from the list. 
From database point of view it does not make any difference.
In the same migration I also changed the name for St Vincent → St Vincent and the Grenadines from the ticket:
https://uktrade.atlassian.net/browse/LTD-1467
since it is related and both report and end user address are being pulled from the same source of countries in database.
SS with GB:
SS with Untied Kingdom removed:
> LTD-1643-Enable the ability to export to Great Britain

- Dockerfile.e2e
- docker-compose.e2e.yml
- makefile
- start-e2e.sh
The intent of this PR is to create a lite-api image that allows us to leave the api app in a state we need it so that it can be published and used in the frontend.
How to test this PR:
- Ensure you are in a clean state by running `docker-compose down`
- Start the new docker setup: `make start-e2e`
- Stop the new docker setup: `make stop-e2e`
> Add dockerfile so it could be published to gcr

- api/users/libraries/notifications.py
- api/users/tests/test_exporter_user_notifications.py
Removing what was added earlier. Fixing missing serial notifications to match with the designs. Adding a banner instead of adding this to existing red dot notifications.
> fixing missing serial notifications to match with the designs

- api/applications/tests/test_standard_application_submit.py
- api/goods/serializers.py
- api/goods/tests/factories.py
- api/goods/tests/test_goods_documents.py
Currently we don't have any option to edit product document availability and sensitivity options as in the current wizard we ask these questions after a product is created.
In the new wizard however we ask these before a product is created and user has an option to edit these from summary screen. So update serializer to be able to save changes and also add unit tests.
> LTD-2156: Update Good serializer to be able to save document related options

- api/goods/helpers.py
Currently if we have a vlid RFD and Section5 certificate then when copying
the data to GoodOnApplication then we are removing certificate number, because
of this the certificate is empty in GoodOnApplication.
> LTD-2310: Copy existing certificate number if there is a valid certificate

- api/audit_trail/serializers.py
- api/cases/tests/test_activity.py
This is to support the following text on the FE notes and timeline -
```
[team-name]: [user-name] did [action]
```
> Add team name for caseworker actors.

- api/cases/tasks.py
- api/cases/tests/test_tasks.py
We were getting non-deterministic code coverage results, even when testing against an empty commit there were cases where the code coverage went down.
This was due to the fact that there were functions being run that would change execution path depending on the day of the week, in this case if the day before was a bank holiday or a weekend it would affect the code coverage.
This pull request adds explicit tests to cover all of the possible execution paths of these date based functions.
> Add explicit tests for date based functions to handle discrepancies on the date the tests are run

- api/applications/models.py
- api/applications/tests/test_models.py
- api/conf/settings.py
Reported in [LTD-2541](https://uktrade.atlassian.net/browse/LTD-2541), there are intermittent instances when a `GoodOnApplication` object is created with values (specifically `control_list_entries`) that seem to be copied over from the associated `Good`. 
It is not obvious where this is happening in the code and why. The purpose of this PR is to provide some visibility about the source of this issue. 
The product implication of the bug is that when TAU officers try to assess the products on a case, they will find that one or more products have already been assessed - because the underlying system relies upon `control_list_entries` on `GoodOnApplication` being `null` when un-assessed.
P.S. this PR is probably temporary, until we hopefully find out the source of LTD-2541, at which point, we …
> [LTD-2541] Goods incorrectly shown as assessed

- api/conf/settings.py
- api/core/helpers.py
- api/core/tests/test_helpers.py
- api/users/notify.py
- api/users/tests/test_create_exporter.py
- api/users/tests/test_notify.py
- api/users/views.py
- gov_notify/enums.py
- gov_notify/payloads.py
- gov_notify/tests/test_enums.py
- gov_notify/tests/test_payloads.py
This change ensures that an exporter user is notified by email when they are added to an organisation.
This uses the following template: https://www.notifications.service.gov.uk/services/f3d8fb42-a34b-4d85-8ac2-a62006a197dc/templates/c9b67dca-0916-453a-99c0-70ba563e1bdd
TODO on merge: Ensure that EXPORTER_BASE_URL and CASEWORKER_BASE_URL are set properly in lite-api's production vault variables.  The default will not work since the URL has private-beta in the name rather than {{env}}
> [LTD-2511] Notify exporter added to organisation

- api/organisations/helpers.py
- api/organisations/notify.py
- api/organisations/tests/test_helpers.py
- api/organisations/tests/test_notify.py
- api/organisations/tests/test_organisations.py
- api/organisations/views/organisations.py
- gov_notify/enums.py
- gov_notify/payloads.py
- gov_notify/tests/test_enums.py
- gov_notify/tests/test_payloads.py
- gov_notify/tests/test_service.py
This change ensures that an exporter user is notified by email when their organisation is approved or rejected.
This uses the following templates:
- approved - https://www.notifications.service.gov.uk/services/f3d8fb42-a34b-4d85-8ac2-a62006a197dc/templates/d5e94717-ae78-4d18-8064-ecfcd99143f1
- rejected - https://www.notifications.service.gov.uk/services/f3d8fb42-a34b-4d85-8ac2-a62006a197dc/templates/1dec3acd-94b0-47bb-832a-384ba5c6f51a
> [LTD-2512] Notify organisation approved or rejected

- api/cases/notify.py
- api/cases/tests/test_case_ecju_queries.py
- api/cases/tests/test_helpers.py
- api/cases/tests/test_notify.py
- api/cases/views/views.py
- api/goods/tests/test_serializers.py
- gov_notify/enums.py
- gov_notify/payloads.py
- gov_notify/tests/test_enums.py
- gov_notify/tests/test_payloads.py
This change ensures that exporter users are notified by email when a query is opened on their application.
The following template is used: https://www.notifications.service.gov.uk/services/f3d8fb42-a34b-4d85-8ac2-a62006a197dc/templates/84431173-72a9-43a1-8926-b43dec7871f9
> [LTD-2514] Notify exporter of ecju query

- api/goods/serializers.py
- api/goods/tests/test_control_codes.py
When a new product is added to an application Exporter can specify CLE for
that product. This may not be the correct one depending on technicalities
and the parties involved for that application so caseworker may/can correct
this as part of their assessment.
Currently if the same product is re-used in some other application we are
replacing previous CLEs with the most recent assessment values.
The requirement is to show all of the previous assessment along with the
recent assessment also to the Exporter hence instead of overwriting we
add to existing values in the case where product is re-used.
> LTD-2453: Retain previously assessed CLEs when a product is re-used in another application

- api/applications/tests/test_application_status.py
- api/applications/views/applications.py
This was originally using the wrong case status (it was using the one that is set when the caseworker opens for editing not the one when the exporter opens for editing)
> Send applicant editing notification

- Pipfile
- Pipfile.lock
- Procfile
- README.md
- api/conf/__init__.py
- api/conf/celery.py
- api/conf/settings.py
- api/core/celery_tasks.py
- api/core/tests/test_celery_tasks.py
- ci.env
- docker-compose.e2e.yml
- docker-compose.yml
- local.env
This change adds celery to lite-api.  
There are a few categories of changes here:
- Redis has been added as a dependency for lite-api.
- Celery library has been added, with a runner which automatically detects celery tasks under `{APP_NAME}/celery_tasks.py` (this avoids collisions with tasks.py which we are already using for django-background-tasks)
- This has been added to the lite-api-dev PAAS environment so far (see instructions for spinning redis/celery up in PAAS here: https://uktrade.atlassian.net/browse/LTD-2526)
- A new celery container will run when running the app through docker-compose.
- Instructions have been added for running celery/redis "on the metal" for non-docker working copies.
- Local running is managed by "watchmedo" which has been installed as a dev dependency; it …
> [LTD-2526] Add celery

- cloudbuild-release.yaml
This creates a new Cloud build file to use within new GCR trigger to allow adding tag to lite-api image during git release
> new cloud build file release GCR trigger

- api/goods/serializers.py
- api/goods/tests/test_edit.py
This is the companion pull request for: https://github.com/uktrade/lite-frontend/pull/815.
This allows fields to be edited on the original good model that are required when attaching. This is part of the "upgrade" process from original goods that didn't have the required section certificate fields added when they were created and we then add them as part of the attaching process.
> Allow editing of section certificate details via attach endpoint

- .coveragerc
- .gitmodules
- Dockerfile.e2e
- api/workflow/README.md
- pii-secret-exclude.txt
This change adds lite-routing as a submodule of lite-api.  This means that tests provided in the contained `routing_rules_internal` package will be run as part of the tests for lite-api.
It also means that lite_routing will be deployed to our environments.
> [LTD-2588] Test routing rules

- api/workflow/automation.py
Currently when routing rules are applied and a Case is moved we don't know
the tier number of the rule applied. Add tier number to understand how
tier number affects routing rules.
> LTD: Add Routing rule tier number to audit event

- api/cases/tests/test_grant_licence.py
- api/cases/tests/test_nlr_licence.py
- api/cases/tests/test_refuse_licence.py
- api/cases/views/views.py
This was removed during Notes and Timeline changes but this affects reporting.
Some of the reports use this event to determine when the case is finalised.
> LTD-2694: Re-instate audit UPDATED_STATUS when case is finalised

- .circleci/config.yml
Added condition if parameter branch_name is not `default` it will trigger the checkout job for CircleCI.
SS if branch_name exists:
> LTD-2644-CircleCI

- test_helpers/clients.py
This is some groundwork for the C5 small arms routing BDD tests: https://github.com/uktrade/lite-routing/pull/32
Ensuring that the `create_standard_application_with_incorporated_good` helper can create an application/goods in the way that we need to.
> Make create_standard_application_with_incorporated_good test helper more configurable

- Pipfile
- Pipfile.lock
Our build/deployment environment seems to no longe have the required postgres source to compile the driver so we are switching to the binary version
> Switch to using psycopg2-binary

- .circleci/config.yml
This should hopefully ensure that our test suite runtime stays manageable.
> Ensure lite_routing tests run in parallel on circleci

- api/applications/serializers/good.py
- api/audit_trail/formatters.py
- api/audit_trail/tests/test_formatters.py
- api/goods/serializers.py
- api/goods/tests/test_control_codes.py
- api/goods/views.py
- api/staticdata/regimes/serializers.py
- api/staticdata/regimes/tests/test_views.py
- api/staticdata/regimes/views.py
- api/workflow/tests/test_flagging_rules.py
This makes setting regime data on a good independent of the flags.
For wassenaar this was simply just handled by setting a flag and then basing the regime on that flag, now we're expanding the available regimes then this isn't going to be a viable strategy going forward.
The old wassenaar flag setting is retained for backwards compatibility whilst the frontend is transitioned to the more granular way of handling regimes.
> Allow updating of regime entries for `GoodOnApplication`

- api/goods/tests/test_control_codes.py
- api/goods/views.py
This is a non-mandatory field and as such we can't guarantee it will exist due to an frontend with older code
> Handle case where `regime_entries` isn't sent through

- .circleci/config.yml
This splits out the lite routing tests into two separate jobs.
This is so that the tests run quicker as they run in parallel.
This also means code coverage isn't run when the lite routing BDD tests run. The BDD tests, beyond the actual things they are asserting, run a lot of incidental code and there is the possibility that this is increasing the code coverage beyond what is actually asserted.
> Run lite routing BDD tests in parallel to unit tests

- api/cases/views/views.py
- api/workflow/automation.py
- api/workflow/user_queue_assignment.py
This change adds `case_status` as an attribute to the payload for MOVE_CASE audit trail events.  This will enable us to add routing rules which fire if a case did/did not visit certain queues when it was in a certain state previously, related PR: https://github.com/uktrade/lite-routing/pull/79
> [LTD-2923] Add case_status to MOVE_CASE audit trail payload

- api/external_data/documents.py
- api/external_data/views.py
This is achieved by adding the model field to `filter_fields`. This will allow the filtering backend to parse the query params for this field and filter the documents. Also added lowercase analyser for this field in case if the country name is in lowercase.
> LTD-2907: Enable filtering Denials search results based on entity country

- manifest.yml
The latest buildpack drops support for the version of Python we have specified in our runtime
Whilst trying to upgrade we wanted to switch the rest of our tooling to match that Python version so that we could fully test against the new intendend Python version however this caused our tests to fail
Given all of the above we have chosen to lock our buildpack version, for now, so that we can fix the rest of our setup and then switch back to an unpinned buildpack
> Lock cloudfoundry Python buildpack

- README.md
Adds instructions for pulling UAT data into your local environment via `cf conduit`.
> Add UAT data pull instructions

- api/workflow/routing_rules/tests/test_routing_rules_creation.py
- api/workflow/routing_rules/tests/test_routing_rules_permissions.py
- api/workflow/routing_rules/tests/test_routing_rules_update.py
- api/workflow/tests/test_automated_case_routing.py
all rules migrated to python criteria
> skip obsolete DB routing rule tests, python rules covered separately

- docker-compose.yml
- local.env
This PR contains 2 commits:
1. [use Administrator role for initial seed of exporter users](https://github.com/uktrade/lite-api/commit/2b9fb8a305e9525213e55734bedccfa3c5230b50) 
Super User was changed to Administrator in this PR https://github.com/uktrade/lite-api/pull/1019
2. [specify linux/amd64 platform in docker-compose](https://github.com/uktrade/lite-api/commit/ee341fd0a2a0b9c5fa1327591f66940eb4844059) 
This enables devs on Mac M1s to run on amd64. Workaround for issue with building against the wrong library version [1]
[1]https://github.com/psycopg/psycopg2/issues/1360
I'm not sure if specifying the default platform in `docker-compose.yml` will break anything for other users, e.g. those running on Windows?
> Docs update

- api/staticdata/regimes/tests/test_views.py
- api/staticdata/regimes/urls.py
- api/staticdata/regimes/views.py
This still keeps the previous URLs intact but redirects to the new URL for backwards compatibility with our frontend until we explicitly make the same change on the frontend
> Consolidate regime entries into a single view

- api/cases/enforcement_check/tests/test_import_xml.py
Fix tests for the Related PR:
https://github.com/uktrade/lite-routing/pull/99
`FAILED api/cases/enforcement_check/tests/test_import_xml.py::ImportXML::test_import_xml_no_match_success - AssertionError: **** is not false`
> LTD-3005-Tests-for-lite-routing

- assets/css/refusal.css
Adjust the width of the sender address column so that the email address will fit on one line when viewed by the exporter
> address width adjustment for refusal letter

- api/applications/tests/test_adding_sites.py
- api/flags/tests/factories.py
This change fixes a couple of tests identified as unreliable by;
- Making FlagFactory much more likely to create a record with a unique name.
- Ensuring a test for sites tests for inequality on id rather than field value.
> [LTD-3152] Fix flaky tests

- Pipfile
- Pipfile.lock
- Procfile
We have had to upgrade to a more recent version of setuptools due to a security advisory
However this version of setuptools requires some extra configuration of the `CFLAGS`
This is fixed in a cf buildpack https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.58 but in this case we are actually outside of the build process
In this case I'm just hardcoding the CFLAGS which is probably quite brittle but it gets the job done
The "obvious" alternative is to just install `endesive` through the usual process but then you end up finding an issue to do with swig which was brought up by SRE two years ago and won't be fixed by cloudfoundry https://github.com/cloudfoundry/python-buildpack/issues/185
> Python setup fatal error

- Procfile
The version of endesive was currently unpinned which means we were always installing the bleeding edge version of endesive
It so happens that the current released version of endesive has a bug which causes signing of PDFs to fail
This problem is further exacerbated due to the fact that this install can happen outside of our managed deployment e.g. when the application is terminated and brought back up again automatically in cloudfoundry
This explicitly pins the version to the same version that we pin to locally
This won't actually have been the last working version of endesive that was deployed to production but is the only version that is a known quantity to us as it's what everyone would have used locally
> Set explicit version of endesive on bringing up web app

- api/parties/serializers.py
- api/parties/tests/test_serializers.py
This is to fix an error where end party url was breaking during validation with a 500 error. 
When a user enters HTTP:// the code would add an additional http:// resulting in a validation error.
The whole string is converted to lower case as urls are inherently lower case anyway
> LTD-3108-end-party-url-validation 

- api/external_data/management/commands/ingest_sanctions.py
- api/external_data/management/commands/tests/test_ingest_sanctions.py
This fixes an issue where the date format across the various sanctions files was different and this was causing OpenSearch to throw an exception when indexing some documents. 
It appears that whatever format is used first in the index is then used as the default for all other documents. 
The fix here is to make sure that the date format is consistent across all documents.
> Ltd 3260 sanctions files

- api/cases/managers.py
- api/cases/tests/test_case_search.py
- api/cases/views/search/views.py
In this frontend PR https://github.com/uktrade/lite-frontend/pull/1049 we are adding tabs beneath the filters on the cases views (both all cases and for specific queues), one tab shows all cases (with whatever filters have been applied) the other tab shows cases that have an ECJU Query that has NOT been responded to by the user.
The tabs will return a query param on the request, and when it is true we want to apply the filter.
> filter cases with open ECJU queries

- api/cases/tests/test_case_search.py
- api/cases/views/search/views.py
Waiting for #1247 to be merged into master.
We would like to show a count of cases with filters possibly applied, on the queue view. This HEAD request allows us to just return the count and avoid extra processing of data.
> LTD-3189: add HEAD request for cases count

- api/cases/managers.py
- api/cases/tests/test_case_search.py
- api/cases/views/search/views.py
[LTD-3239](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3239)
The frontend for the cases/queues view is going to have several tabs that aim to filter out cases. We have already introduced the 'all cases' and 'open queries' tabs, but now that one more is being added ('my cases') we need to change the way the logic for filtering is handled (it's not either/or anymore).
[Together with this Frontend PR](https://github.com/uktrade/lite-frontend/pull/1064) I'm proposing:
_on the frontend_
1. instead of a param for each tab (e.g. `only_open_queries`) we have a param whose value is the selected tab e.g. `selected_tab=open_queries`
2. in the view, to get a count for each tab, we the tab names and make a HEAD request to get the count like we …
> LTD-3239: Add a 'my cases' tab/filter

- api/cases/serializers.py
- api/cases/tests/test_case_search.py
Extends the existing case search API endpoint as follows;
- Adds a `queues` field to case results returned so that callers are able to determine which queues a case is present on.
- Extends the `assignments` field value so that the team_id is returned for each assignment.
- Extends the `assignments` field value so the queues that the user is assigned on are expressed as an object (id/name) rather than just a string field (name) as previous.
- Note that technically this is a backward compatibility breaking change, however it turns out that the frontend does not consume this particular field as it stands so it will not result in a breakage if old FE is consuming new API.  Due to this we should ensure that this API change is released before releasing the frontend change.
Companion frontend …
> Adjust case search API to respond with assigned queues

- api/staticdata/report_summaries/serializers.py
- api/staticdata/report_summaries/tests/test_views.py
- api/staticdata/report_summaries/urls.py
- api/staticdata/report_summaries/views.py
- api/staticdata/urls.py
In order for the frontend to populate the report summary prefix and subject search fields, we need endpoints on the API.
> API endpoint for getting Report Summary data

- api/users/migrations/0003_default_govuser_queue.py
This fixes an error (manifested here; https://github.com/uktrade/lite-api/blob/dev/api/gov_users/serializers.py#L98:L104) which was the result of removing the "My assigned cases" system queue.
> Fix GovUsers who have default_queue pointing to removed system queue

- .circleci/config.yml
This fixes the `check-lite-routing-sha` circleci job which was using master as a base rather than dev.
> Fix lite-routing commit sha checker CI job

- api/cases/tests/views/search/test_service.py
- api/cases/views/search/service.py
- api/cases/views/search/views.py
add recent activity column to cases page
-enhanced cases templates to include extra data from the api
compared getting data via api using several queries and this appeared to be the quickest when run on local environment.
We needed last 2 audit activities per case but the case_id could be an action object or target object. Alternatives tried:
using union to get correct results from the fb
using filter to get last 2 activities per action and target (total 4) and filtering down to 2
a few different methods of massaging the data after retrieving results
> Ltd 3190 case status detailed

- api/staticdata/report_summaries/helpers.py
- api/staticdata/report_summaries/tests/test_views.py
- api/staticdata/report_summaries/views.py
This PR adds name filtering to the report_summary prefix and subject endpoints.
Ordering is by prefixed results first and then alphabetically.
> Report Summary endpoint filtering

- api/external_data/serializers.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
[Ticket](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3294) 
The Denials search was only returning the first 10 results, this adds pagination to the view. 
~~The lite-routing test needs to be skipped first: https://github.com/uktrade/lite-routing/pull/131 ✅~~
~~The lite-routing test needs to temporarily accept both types of json results https://github.com/uktrade/lite-routing/pull/133 ✅~~
this lite routing test fix needs merging https://github.com/uktrade/lite-routing/pull/134/files ✅  
Then the SHA needs to be updated: https://github.com/uktrade/lite-api/pull/1304 ✅    
Then this PR merged ✖️ 
And frontend merged: https://github.com/uktrade/lite-frontend/pull/1095 ✖️ 
Then the test needs to be fixed: …
> Denials pagination

- api/goods/tests/test_control_codes.py
- api/goods/views.py
- api/staticdata/report_summaries/tests/factories.py
- api/staticdata/report_summaries/tests/test_views.py
- api/staticdata/report_summaries/urls.py
- api/staticdata/report_summaries/views.py
This adds two new endpoints to get details for the report summary objects.
This is so that it can be used on the frontend to check whether an id for a report summary object exists, this is used to validate the data in the assessment form.
There are also some changes here to fix a bug where a blank report summary prefix could be sent through and that would result in an error.
> Ltd 3262 report summary

- api/cases/tests/test_case_search.py
- api/cases/views/search/service.py
- api/gov_users/serializers.py
- api/organisations/serializers.py
- api/organisations/tests/test_sites.py
- api/organisations/views/users.py
- api/users/models.py
- api/users/serializers.py
Part 1
- add pending @property to model/serializer/endpoints based off of user.firstname
- swap out logic on frontend to use new pending field
Part 2
- swap out pending @property to be an actual DB field that’s updated when user first logs in
Related ticket to the FE:
https://github.com/uktrade/lite-frontend/pull/1101
> LTD-3028-Adds-property

- api/staticdata/statuses/enums.py
We want to allow exporter users to edit cases when they are under review, because this is when officers can ask them to make changes.
This is covered by already existing tests in https://github.com/uktrade/lite-api/blob/f4b7f9d3552bcc94375697cbb0967336049f227c/api/applications/tests/test_edit_application.py 
> LTD-3305: remove `UNDER_REVIEW` from read only statuses

- .circleci/config.yml
- generate_cucumber_report.js
This gives us better reporting of what failed when the routing BDD tests fail.
This does the following:
- Outputs the full scenario in the logs on CircleCI
- Uploads xunit test results to CircleCI to tell us exactly what failed
- Produces a HTML report that will show us exactly what scenarios failed and what steps failed
This is mostly all helping in regards to reporting on CircleCI, however when running locally we can use the same gherkin reporter to give us a better representation as to what's failing.
I've not made the gherkin reporter the default in anyway as I feel it should be up to the developer themselves to choose to run this if they so wish.
[LTD-3454](https://uktrade.atlassian.net/browse/LTD-3454)
[LTD-3454]: https://uktrade.atlassian.net/browse/LTD-3454?atlOrigin=eyJpIjoiNWRkNT …
> Update BDD tests output

- .circleci/config.yml
Run the e2e tests on API changes.
This is to handle the case where an API change may break the e2e tests.
We call the `lite-frontend` pipeline specifying the branch of the API changes and attempt to run them against the frontend `dev` branch.
To begin with I am going to keep this job as being not required on our CI checks so that we can see if this causes any issues.
[LTD-3455](https://uktrade.atlassian.net/browse/LTD-3455)
[LTD-3455]: https://uktrade.atlassian.net/browse/LTD-3455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Run E2E tests on API changes

- .circleci/config.yml
- api/conf/settings.py
- api/conf/settings_test.py
- pytest.ini
Update the default configuration when running tests to make output less verbose. This is especially important when a test fails so that the information about the error is the easiest thing to find.
This turns off most of the default logging and capturing that was occurring when we were running the tests.
The following has been changed:
- disable capturing and outputting warnings during tests
- disable capturing and outputting stdin/stdout during tests
- disable all loggers during tests
- suppress output of seeding commands
[LTD-3453](https://uktrade.atlassian.net/browse/LTD-3453)
[LTD-3453]: https://uktrade.atlassian.net/browse/LTD-3453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 3453 output logging

- api/staticdata/statuses/tests/test_statuses.py
we recently wanted to change the `under_review` status to read only, and
assumed that it was just a matter of changing the CaseStatusEnum, but it
turned out to need a migration on the CaseStatus model.
There are tests in `test_edit_application` that provide more integration
testing for both `read_only` and `editable` cases, but these make sure
that the Enum will always match what's on the database.
> unit tests to cover `CaseStatus` and `CaseStatusEnum`

- api/applications/serializers/advice.py
There was a situation where we believed that denial reasons were getting deleted and warning logs were added in few places. This was one such instance.
A new put method is going to be added to actually update Advice objects and this warning will be triggered with each update which is not very useful hence removing this.
[LTD-3499](https://uktrade.atlassian.net/browse/LTD-3499)
[LTD-3499]: https://uktrade.atlassian.net/browse/LTD-3499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-3499: Remove warnings on update about denial reasons

- api/teams/enums.py
This is a subtask of the work in this PR: https://github.com/uktrade/lite-routing/pull/162
[LTD-3500](https://uktrade.atlassian.net/browse/LTD-3500)
[LTD-3500]: https://uktrade.atlassian.net/browse/LTD-3500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Create LU TeamIdEnum in lite-api

- api/staticdata/countries/factories.py
There were some cases in our BDD scenarios which used Spain as a country, however this factory would sometimes go and generate a second Spain object in the database due to the fact that the country code for Spain was incorrect and the database would end up with two countries with the name Spain.
This now uses the correct country code for Spain in the factory so that only one Spain object exists.
> Use correct country code for Spain to avoid duplicated country

- .bandit
- .circleci/config.yml
This change does two things;
- Ensures that lite-routing PRs run linting checks properly.  Previously the linting step would not check out the custom lite-routing branch, this has been swapped to use `setup` (which checks out the custom lite-routing branch) like other steps.
- Stops bandit checking `conftest.py` - bandit is a tool for security assurance and should not be run against test code.
> Ensure linting checks run against lite-routing PRs

- api/staticdata/statuses/enums.py
- api/staticdata/statuses/tests/test_statuses.py
The new statuses introduced for LU Countersigning are behind a feature flag so we need to evaluate these at runtime (when running tests) otherwise they don't get picked up and tests fail.
> LTD-3481: Update CaseStatusEnum to evaluate status choices at runtime

- api/applications/tests/test_finalise_application.py
- api/applications/views/helpers/advice.py
- api/cases/tests/test_edit_advice.py
- makefile
Currently a check in the finalise view prevents the finalising of REFUSE advice if there are LU countersigning flags present.
This PR removes that check and associated tests.
[LTD-3573](https://uktrade.atlassian.net/browse/LTD-3573)
[LTD-3573]: https://uktrade.atlassian.net/browse/LTD-3573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Removed the check for lu countersignatures

- api/audit_trail/formatters.py
- api/audit_trail/tests/test_formatters.py
- api/cases/libraries/post_advice.py
- api/cases/tests/test_create_advice.py
Licence conditions (Proviso advice) should be audited. Audit messages should be as per the designs in the ticket and "additional text" to display in the timeline should be the proviso text.
[LTD-3485](https://uktrade.atlassian.net/browse/LTD-3485)
[LTD-3485]: https://uktrade.atlassian.net/browse/LTD-3485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Proviso audit

- api/audit_trail/formatters.py
- api/audit_trail/tests/test_formatters.py
- api/cases/tests/test_create_advice.py
Duplicate names were appearing in the audit logs. This is caused by the name in the template as well as being automatically prepended to messages in the timeline view.
[LTD-3485](https://uktrade.atlassian.net/browse/LTD-3485)
[LTD-3485]: https://uktrade.atlassian.net/browse/LTD-3485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Duplicate name fix uat

- api/audit_trail/formatters.py
- api/audit_trail/tests/test_formatters.py
- api/cases/tests/test_create_advice.py
Duplicate names were appearing in the audit logs. This is caused by the name in the template as well as being automatically prepended to messages in the timeline view.
[LTD-3485](https://uktrade.atlassian.net/browse/LTD-3485)
[LTD-3485]: https://uktrade.atlassian.net/browse/LTD-3485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove duplicate names from audit template

- api/cases/tests/test_get_case.py
- api/cases/views/views.py
This fixes a production issue where the case details page isn't loading when an application is a copy of another.
There is a prefetch related call that can't actually be prefetch related and so I've removed it.
[LTD-3637](https://uktrade.atlassian.net/browse/LTD-3637)
[LTD-3637]: https://uktrade.atlassian.net/browse/LTD-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add test for getting a copied cases details

- Dockerfile
When running docker on my machine I have to rebuild the containers for any changes to take effect.
This prevents that issue by no caching settings for python.
> fix-django-docker-caching-issue 

- api/cases/managers.py
- api/cases/serializers.py
- api/cases/tests/test_case_search.py
- api/cases/views/search/service.py
- api/cases/views/search/views.py
This change adds the following fields to the cases search response;
- `goods` - details of the goods present on the case
- `denials` - details of denial matches for the case
- `ecju_queries` - details of ECJU queries present on the case
- `intended_end_use` - the intended end use picked out from the case's related application model
This is used in the companion frontend PR: https://github.com/uktrade/lite-frontend/pull/1255
[LTD-3626](https://uktrade.atlassian.net/browse/LTD-3626)
[LTD-3626]: https://uktrade.atlassian.net/browse/LTD-3626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-3626] Add goods/denials/queries/end use to cases search response

- api/cases/serializers.py
- api/cases/tests/test_case_notes.py
- api/cases/urls.py
- api/cases/views/case_notes.py
- api/cases/views/search/activity.py
- api/cases/views/views.py
- test_helpers/clients.py
https://uktrade.atlassian.net/browse/LTD-3654
This API call has been linked with the notes and timelines screen. 
The mentions portion will pull the mentions on a screen and display as per requirements. We could have used the same data shape as the Audit Table but I believe this is fundamentally wrong and a bit of a hack. Hence a new API call to pull real data from the source table.
>  LTD-3654-pull-mentions-data 

- api/cases/models.py
- api/cases/tests/test_get_case.py
Case parameter_set() is used to check for countersigning flags and if they are present we ensure necessary countersignatures are present when the case is finalised. However it currently doesn't ignore any deleted parties on the application. If that party destination is the only one that needs countersigning then can block finalising even though that party is deleted.
Ignore deleted parties as they are no longer valid on the application.
> LTD-3686: Ignore deleted parties when determining Case parameter_set

- api/cases/serializers.py
- api/cases/tests/test_case_notes.py
- api/cases/urls.py
- api/cases/views/case_notes.py
https://uktrade.atlassian.net/browse/LTD-3699
This adds a new end point which allows bulk update of case note mentions. 
Predominantly used to update the is_accessed flag. This is extending a new view ideally the get and patch could be in a single view. However the get is making use of the DRF ListAPIView and the new can't be mixed. 
I will add in a jira to collapse these into a single view.
>  LTD-3699-is-new-reset 

- api/cases/tests/test_case_notes.py
- api/cases/urls.py
- api/cases/views/case_notes.py
A count of new mentions for a user is required in the UI menu.
Hence a light weight API call just to get a count.  I did think about making this more generic or extend one of the other review for filtering. But figured this is used so often and is imperative to the application functioning it's worth having it's own API call.
>  LTD-3741-api-call-new-mentions 

- api/cases/managers.py
- api/cases/tests/test_case_search.py
- api/cases/views/search/views.py
Adjust case search API to provide filters for `export_type` and `assigned_queues` as required for case search changes.
[LTD-3796](https://uktrade.atlassian.net/browse/LTD-3796)
[LTD-3796]: https://uktrade.atlassian.net/browse/LTD-3796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-3796] Queue view filters case

- api/conf/settings.py
- api/core/tests/test_views.py
- test_helpers/helpers.py
Disable Django admin by default. This is to ensure that it's not switched on for environments it shouldn't be whilst retaining the ability for it to be toggled on as required such as for local development.
[LTD-3762](https://uktrade.atlassian.net/browse/LTD-3762)
[LTD-3762]: https://uktrade.atlassian.net/browse/LTD-3762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set Django admin to be toggled via env variables

- api/cases/managers.py
- api/cases/tests/test_case_search.py
Add capability to cases search endpoint for filtering by ~~`organisation_site_country`~~ `goods_starting_point`
> Add support for filtering case search by goods_starting_point

- api/cases/managers.py
- api/cases/tests/test_case_search.py
Add support for filtering case search results by two extra fields;
- `exclude_denial_matches` - exclude cases which have denial matches.
- `exclude_sanction_matches` - exclude cases which have sanction matches.
[LTD-3799](https://uktrade.atlassian.net/browse/LTD-3799)
[LTD-3799]: https://uktrade.atlassian.net/browse/LTD-3799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-3799] Queue view parties filters

- api/cases/managers.py
- api/cases/tests/test_case_search.py
- api/cases/views/search/views.py
Add support for `max_total_value` filter in case search API; enabling callers to get cases who's goods amount to less than this total value.
[LTD-3827](https://uktrade.atlassian.net/browse/LTD-3827)
[LTD-3827]: https://uktrade.atlassian.net/browse/LTD-3827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-3827] Add case search filter for max_total_value

- api/staticdata/regimes/views.py
This change ensures that the API to get all regimes is sped up by introducing select_related calls.
> Optimise regimes API endpoints

- api/cases/managers.py
- api/cases/tests/test_case_search.py
- api/cases/tests/test_case_search_advanced.py
- api/cases/views/search/views.py
Add support for filtering by one or more countries to case search API. 
[LTD-3899](https://uktrade.atlassian.net/browse/LTD-3899)
[LTD-3899]: https://uktrade.atlassian.net/browse/LTD-3899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-3899] Add support for filtering by multiple countries in case search API

- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
- api/goods/tests/factories.py
Allow cases to be searched by text contained in either report summary prefix or subject for goods on that case.
[LTD-3831](https://uktrade.atlassian.net/browse/LTD-3831)
[LTD-3831]: https://uktrade.atlassian.net/browse/LTD-3831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Case search - Report summary support

- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
This change replaces the goods type description search parameter with product_type to support the change in frontend filter.
[LTD-3832](https://uktrade.atlassian.net/browse/LTD-3832)
[LTD-3832]: https://uktrade.atlassian.net/browse/LTD-3832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Do not check goods_type for product name, but do check product name

- api/conf/settings.py
Stop Sentry alerts complaining about an unfound admin route.
This will ensure that SSO is only switched on if admin is switched on as well (the only reason to turn on SSO would be for Django admin anyway).
[LTD-3902](https://uktrade.atlassian.net/browse/LTD-3902)
[LTD-3902]: https://uktrade.atlassian.net/browse/LTD-3902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Only turn on SSO if admin is also turned on

- api/cases/helpers.py
- api/cases/managers.py
- api/cases/tests/test_case_search.py
Ensure that "assignment" filter for case search API takes in to account the queue filter parameter.  This means that assignment filtering will be scoped to assignments which are for the filtered queue; with the exception of the "all cases" queue as it makes sense to look at **all** case allocation records for that queue.
[LTD-3936](https://uktrade.atlassian.net/browse/LTD-3936)
[LTD-3936]: https://uktrade.atlassian.net/browse/LTD-3936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-3936] Ensure that cases search API assignment filter considers current queue

- api/applications/tests/test_copy_application.py
- api/cases/managers.py
- api/cases/serializers.py
- api/cases/tests/test_case_search.py
- api/flags/tests/test_case_view_flag_ordering.py
- test_helpers/clients.py
Added end-users / ult-end-users to the case payload
This is to enable the frontend to display the end-users in a configurable column in the queue display.
[LTD-3960](https://uktrade.atlassian.net/browse/LTD-3960)
[LTD-3960]: https://uktrade.atlassian.net/browse/LTD-3960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added end-users / ult-end-users to the case payload

- api/cases/models.py
- api/cases/tests/test_create_advice.py
- api/cases/tests/test_edit_advice.py
Stop denial reasons from being deleted.
[LTD-4030](https://uktrade.atlassian.net/browse/LTD-4030)
[LTD-4030]: https://uktrade.atlassian.net/browse/LTD-4030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Retain denial reasons after advice has been countersigned

- api/cases/generated_documents/tests/factories.py
- api/cases/generated_documents/tests/test_views.py
- api/cases/generated_documents/urls.py
- api/cases/generated_documents/views.py
- api/cases/notify.py
- api/cases/tests/test_notify.py
- gov_notify/enums.py
- gov_notify/payloads.py
- gov_notify/tests/test_enums.py
- gov_notify/tests/test_payloads.py
Add API endpoint for sending generated case documents to exporters; the endpoint marks a document as `visible_to_exporter=True` and sends a notification if a notification would be applicable for the given template.  For now, only generated docs from the "inform_letter" template will result in a notification - but we can extend this as we use this endpoint for more documents in the future.
[LTD-4056](https://uktrade.atlassian.net/browse/LTD-4056)
[LTD-4056]: https://uktrade.atlassian.net/browse/LTD-4056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4056] Endpoint to send generated case documents to exporters 

- api/cases/generated_documents/serializers.py
- api/cases/tests/test_final_advice_documents.py
Ensure `visible_to_exporter` is present on documents in final advice documents API response.  This is necessary for showing/hiding the "Send to exporter" button for inform letter on the frontend.
[LTD-3938](https://uktrade.atlassian.net/browse/LTD-3938)
> [LTD-3938] Inform letter send

- api/cases/tests/test_refuse_licence.py
This Updates the tests during refusal finalisation to ensure we can proceed with just a refusal letter
https://uktrade.atlassian.net/browse/LTD-4142
> LTD-4142-update-test-to-confirm-finalisation-no-inform

- api/appeals/tests/factories.py
- api/applications/tests/test_appeal.py
- api/applications/urls.py
- api/applications/views/applications.py
Add detail endpoint to get information about an appeal.
This also renames the create endpoint to situate it under a "list" endpoint.
[LTD-4125](https://uktrade.atlassian.net/browse/LTD-4125)
[LTD-4125]: https://uktrade.atlassian.net/browse/LTD-4125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add detail endpoint for application appeal

- api/cases/generated_documents/serializers.py
- api/cases/generated_documents/tests/test_views.py
- api/cases/generated_documents/views.py
Add a serialized document to the "send generated document" endpoint response.
[LTD-4160](https://uktrade.atlassian.net/browse/LTD-4160)
[LTD-4160]: https://uktrade.atlassian.net/browse/LTD-4160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4160] Add document to generated document send endpoint response

- api/cases/models.py
- api/cases/tests/test_models.py
Ensure case sub-status is reset when case status is changed.  This adds to our existing post save case signal.
[LTD-4189](https://uktrade.atlassian.net/browse/LTD-4189)
[LTD-4189]: https://uktrade.atlassian.net/browse/LTD-4189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4189] Ensure case sub-status is reset on status change

- api/applications/models.py
- api/applications/tests/test_appeal.py
Set sub-status when a case has been appealed. 
[LTD-4233](https://uktrade.atlassian.net/browse/LTD-4233)
[LTD-4233]: https://uktrade.atlassian.net/browse/LTD-4233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set sub-status when case has been appealed

- api/cases/management/commands/convert_nlr_advice_to_refuse.py
- api/cases/management/commands/tests/test_convert_nlr_advice_to_refuse.py
Add a re-usable management command to convert erroneous NLR final advice to refusal advice.
[LTD-4219](https://uktrade.atlassian.net/browse/LTD-4219)
[LTD-4219]: https://uktrade.atlassian.net/browse/LTD-4219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4219] Add management command to convert NLR final advice to refused

- api/letter_templates/context_generator.py
- api/letter_templates/tests/test_context_generation.py
This is a fix for the production issue where licence quantities and values were not showing on the generated licence document. This affected multiple exporters who raised the issue to lite support.
After initial investigation it looked as if the issue was appearing only for PROVISO licences. Due to an earlier change which fixed the variable output in the generated document from `applied_for_quantity`  and `applied_for_value` to `quantity` and `value` taken from the good on licence, the quantity and value was not showing on the generated licence document.
The problem is in the way PROVISO good data are combined with APPROVE good data in the context generator.
This PR fixes the issue in a way that makes sure we are still using the correct data taken from the good on licence, but combines …
> Fix licence document quantity value not showing

- api/cases/tests/test_good_precedents_view.py
- api/cases/views/views.py
- api/goods/serializers.py
This PR ensures that the following fields are present on the precedent API endpoint response;
- `is_good_controlled`
- `is_ncsc_military_information_security`
- `report_summary_prefix`
- `report_summary_subject`
- `comment`
This will enable the "previous assessments" page to show previous assessments in full and enable us to submit a previous assessment as the new assessment for a product on an application.
[LTD-4277](https://uktrade.atlassian.net/browse/LTD-4277)
[LTD-4277]: https://uktrade.atlassian.net/browse/LTD-4277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4277] Add various fields to precedent API response

- api/applications/tests/test_application_sub_status.py
- api/applications/views/applications.py
https://uktrade.atlassian.net/browse/LTD-4305
remove 'none' in audit log working when reseting sub status
>  LTD-4305-remove-none-sub-status-audit-log 

- Procfile
- apt.yml
- manifest.yml
This explicitly sets versions for the cf stack and swig in preparation for the cflinuxfs4 upgrade
These are currently the implicit versions but it's once we upgrade the stack and swig version these changes become "sticky" and mean that even if we try to rollback we can still be stuck with these versions, if these are set explicitly then if we need to rollback it will rollback to these specific versions
> Stabilise to configuration for cflinuxfs3 and swig

- api/cases/management/commands/sla_processing_time_report.py
- api/cases/management/commands/tests/test_sla_processing_time_report.py
- test_helpers/clients.py
https://uktrade.atlassian.net/browse/LTD-4289
This is a WIP 
Currently this is a skeleton report which can be used to  :
- Update SLA, alter or create orginal_submission_date numbers historically 
- Create a report for all deals with SLA days to compare against submission of SLA's published historically. This will be required for business sign-off
Above will be done via management commands and migrations
improvements to follow:
- Check if a case is within SLA time parameters before adding days
- Check if a ECJU is within SLA time parameters before subtracting days
>  LTD-4282-report-sla-numbers

- Procfile
- apt.yml
- manifest.yml
This is to upgrade to this particular stack before gov paas forcibly upgrades for us in November
This makes the following changes to ensure the new stack works:
- Adds an explicit version of swig - When the new stack is set this automatically starts using swig4.0 instead of swig3.0, to ensure consistency with future rollouts I have pinned the version here
- Adds the the SWIG_LIB env to the Procfile
- This was originally set in vault and was pointing to the swig3.0 directory, to make sure this is more obvious I have added this explicitly to the Procfile
- swig is required to install pykcs which is a sub-dependency of endesive
> Update stack to cflinuxfs4

- Dockerfile
- docker-compose.yml
This is so that we can have a development environment that is more consistent with our production environments
Match linux versions to what's on cloudfoundry
> Match the docker linux version that's on cloudfoundry

- api/cases/tests/test_good_precedents_view.py
- api/cases/views/views.py
Ensure the precedents API excludes GoodOnApplication entries with `is_good_controlled=None` from results.  These are either unassessed GoodOnApplication records or pre-date `is_good_controlled` being set on assessment, so it is best to exclude them from precedents.
[LTD-4359](https://uktrade.atlassian.net/browse/LTD-4359)
[LTD-4359]: https://uktrade.atlassian.net/browse/LTD-4359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4359] Ensure precedents API excludes products with is_good_controlled=None

- api/search/product/documents.py
- api/search/product/tests/test_views.py
- api/search/product/views.py
Add Applicant (organisation) and assessment note to the list of fields to search.
Simple and related changes so combined into a single PR.
[LTD-4333](https://uktrade.atlassian.net/browse/LTD-4333)
[LTD-4335](https://uktrade.atlassian.net/browse/LTD-4335)
[LTD-4333]: https://uktrade.atlassian.net/browse/LTD-4333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-4335]: https://uktrade.atlassian.net/browse/LTD-4335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4333-4335: Add option to search by applicant and assessment note

- api/search/product/documents.py
- api/search/product/serializers.py
- api/search/product/tests/test_views.py
- api/search/product/views.py
Update the product search API to support searching by regime. Both the regime `name` and `shortened_name` can be searched on.
[LTD-4330](https://uktrade.atlassian.net/browse/LTD-4330)
[LTD-4330]: https://uktrade.atlassian.net/browse/LTD-4330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add option to search by regime

- api/cases/generated_documents/tests/test_views.py
- api/search/product/tests/test_views.py
Fixing tests where reference numbers don't match 
this could possibly be due to uncleaned up data
>  fix-GeneratedDocumentSendTests 

- Dockerfile
- api/assessments/serializers.py
- api/assessments/tests/test_views.py
- api/assessments/urls.py
- api/assessments/views.py
- api/conf/settings.py
- api/conf/urls.py
- api/goods/views.py
The aim with this change is to create a new endpoint for creating bulk TAU assessments of goods.  The existing goods assessment endpoint has two major drawbacks;
- It does not accept bulk distinct assessments (just a single assessment applied to multiple GoodOnApplication records).
- It is slow.
The new endpoint created in this PR has aimed to port over all of the necessary functionality from the old endpoint while leaning more on django rest framework to make things much cleaner.
For previous assessment submissions (companion PR; https://github.com/uktrade/lite-frontend/pull/1606), response time for submitting 27 assessments has dropped from ~22seconds to under 3 seconds.
Further time savings to get this example under 1 second are possible, but rely on us improving search document …
> [LTD-4352] Bulk distinct assessments endpoint

- api/cases/tests/test_good_precedents_view.py
- api/cases/views/views.py
- api/staticdata/statuses/enums.py
Ensure previous assessment table only shows assessments from cases that went past TAU
This adds filtering by status, so any statuses after TAU should be filtered out - it's acknowledged in the original ticket that to not be perfect - status may not be the only thing that decides this - but in practice, for the assessments here this gets us most of the way there.
> LTD-4395 - Ensure previous assessment table only shows assessments from cases that went past TAU

- api/search/product/serializers.py
- api/search/product/tests/test_views.py
- api/search/product/views.py
We define an elastic search document type based on a model which allows to index the fields we are interested in.
These are later useful to perform searches based on those fields and results contain the fields specified in the document.
However we have requirement where we want to show additional details from the model which are not necessarily index and made available for search.
To achieve this we need to augment the search results (hits) with model instances so that at the time of generating the response we can include additional fields using the model instance.
In this case we override the `list()` method that the plugin uses and hydrate the results with additional fields.
[LTD-4429](https://uktrade.atlassian.net/browse/LTD-4429)
[LTD-4429]: …
> Augment search results with model instances

- api/external_data/management/commands/ingest_sanctions.py
Fix SSL connection issue with UN sanctions web server
This appears to have happened due to us upgrading our cryptography library for a security patch
The fix for this comes from https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled
[LTD-4436](https://uktrade.atlassian.net/browse/LTD-4436)
[LTD-4436]: https://uktrade.atlassian.net/browse/LTD-4436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix SSL connection issue with UN sanctions web server

- api/external_data/management/commands/ingest_sanctions.py
- api/external_data/management/commands/tests/test_ingest_sanctions.py
Fix issues where data coming from the sanctions third party data is missing certain pieces of data.
In these cases we either fallback to another piece of data or just ignore that particular row.
[LTD-4439](https://uktrade.atlassian.net/browse/LTD-4439)
[LTD-4439]: https://uktrade.atlassian.net/browse/LTD-4439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 4439 uk sanctions name

- api/search/product/documents.py
- api/search/product/tests/test_helpers.py
- api/search/product/tests/test_views.py
Index only the ratings provided by TAU.
Exporter suggested ratings need not be indexed.
[LTD-4434](https://uktrade.atlassian.net/browse/LTD-4434)
[LTD-4434]: https://uktrade.atlassian.net/browse/LTD-4434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4434: Index only TAU rated control list entries

- api/search/product/serializers.py
- api/search/product/tests/test_views.py
- api/users/models.py
We index `assessed_by` but it is better if we expose this from model instance as this field can be `None` and we can perform all the checks in the serializer and return a value to just display in the template.
[LTD-4475](https://uktrade.atlassian.net/browse/LTD-4475)
[LTD-4475]: https://uktrade.atlassian.net/browse/LTD-4475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4475: Add assessing officer details from model instance

- api/search/product/tests/test_helpers.py
- api/search/product/tests/test_views.py
- api/search/product/urls.py
- api/search/product/views.py
To help users specify a data category when performing a search we are providing suggestions by checking which fields given search term matches with. This is done using multi match prefix query where prefix match is performed on each word. Highlight indicates where given search term is matched and these fields are returned as suggestions.
[LTD-4468](https://uktrade.atlassian.net/browse/LTD-4468)
[LTD-4468]: https://uktrade.atlassian.net/browse/LTD-4468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4468: Add endpoint to provide suggestions for the search terms

- api/search/product/views.py
We run a query to retrieve suggestions for the given search string and specify the number of maximum results which is 15 at the moment.
In some cases eg for destinations we could get many hits. In case of consignee, end-user and ultimate end-users if the destination is same for all these parties, depending on the total number of applications for these destinations total count may well exceed 15 and we may not include certain party types hence we miss showing either one or more of these party types in some cases.
Increase the count to 30 to make sure all categories are included in suggestions.
It is to be noted that this is the maximum number of hits so we may not always get this number of hits. Also we limit the number of suggestions to show in frontend which is 10. …
> LTD-4511: Increase the maximum number of suggestions retrieved from the query

- api/gov_users/serializers.py
- api/gov_users/tests/test_serializers.py
This caches the queue objects upfront so that this serializer doesn't need to do a queue lookup each time it's accessed
This is particularly useful when this serializer is called multiple times per page
> Cache queue objects on gov user serializer

- api/search/product/views.py
Assessment note can be very long; searching and looking for suggestions in this doesn't provide much value. It is also difficult to edit query string if a suggestion related to assessment_note is selected.
[LTD-4525](https://uktrade.atlassian.net/browse/LTD-4525)
[LTD-4525]: https://uktrade.atlassian.net/browse/LTD-4525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4525: Don't show suggestions for assessment_note

- api/applications/serializers/advice.py
Add a custom user serializer that doesn't have the role nested serializer for countersign advice.
This is due to the fact that this ends up being a deeply nested serializer that ends up creating a significant number of unused objects (~20,000). Removing this causes a significant speed improvement.
[LTD-4530](https://uktrade.atlassian.net/browse/LTD-4530)
[LTD-4530]: https://uktrade.atlassian.net/browse/LTD-4530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use custom serializer for countersign user

- api/search/product/views.py
This is due to the fact that we collapse down the number of results to make them unique so given a lot of duplicates we might end up with far fewer results than we expect
From testing in some cases starting off with 30 only return 5 results after collapsing for uniqueness
To work around this we're just grabbing a larger number from opensearch to ensure we get a larger number of results after the unique filter
This could still potentially bring back fewer results than we want but this is a quick fix to solve the problem
> Increase the number of product suggestions we obtain from opensearch

- api/search/product/tests/test_views.py
- api/search/product/views.py
This is a small API change to the product search invalid query 400 response that enables a fix to the error content in the frontend.
[LTD-4537](https://uktrade.atlassian.net/browse/LTD-4537)
[LTD-4537]: https://uktrade.atlassian.net/browse/LTD-4537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix invalid query 400 response

- api/search/product/tests/test_views.py
- api/search/signals.py
- api/search/tasks.py
- api/search/tests/test_signals.py
- api/search/tests/test_tasks.py
Updates the various models are intercepted in save() signal to refresh the indexes however it is only updating Application document.
When an application is first submitted by Exporter we run flagging rules which result in saving of underlying 'Good' instances. At this point the ProductDocument is not refreshed so if we search for a product in this application we see the reference_code as None as if it is still in draft state. Updating product document here pulls inner document for the Application with the updated reference code.
Without this change also eventually the reference code gets refreshed as the application progresses through various teams which result in updating of product attributes but if it is in submitted state then it doesn't get updated. …
> LTD-4534: Update search signals to refresh Product document also

- api/assessments/serializers.py
- api/assessments/tests/test_views.py
- api/cases/generated_documents/tests/test_generate_document.py
TAU users are currently unable to clear assessments following the most recent changes to the assessment endpoint.  This change ensures that clear assessments works as intended.
[LTD-4576](https://uktrade.atlassian.net/browse/LTD-4576)
[LTD-4576]: https://uktrade.atlassian.net/browse/LTD-4576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4576] Fix clear assessments endpoint

- api/search/signals.py
- api/search/tasks.py
- api/search/tests/test_signals.py
The task needs to be called with args that are JSON encodable as this is how background_task will save the args to run the task later
> Fix calling update search index task

- api/cases/views/views.py
- api/licences/celery_tasks.py
- api/licences/libraries/hmrc_integration_operations.py
- api/licences/tests/test_api_to_hmrc_integration.py
The task that sends licence details to lite-hmrc is scheduled when licence is issued which is already part of a transaction.
Licence row would've already been locked during that transaction so if continue without waiting it will result in `OperationalError`.
[LTD-4561](https://uktrade.atlassian.net/browse/LTD-4561)
[LTD-4561]: https://uktrade.atlassian.net/browse/LTD-4561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4561: Wait till the lock is available before updating Licence table

- Pipfile
- Pipfile.lock
- api/cases/models.py
- api/cases/serializers.py
- api/cases/tests/test_case_ecju_queries.py
- api/cases/tests/test_case_search.py
https://uktrade.atlassian.net/browse/LTD-4616
A new property is added to ECJUQuery object currently when a query is being tested for closure it's inconsistent 
as the code checked response is null , response_at is null. This property decouples these checks so we can test within the model. 
The are further designs coming into scope where an exporter can close a query without having a response. So this will allow the model to support this change.
> LTD-4616-add-is-query-closed-property 

- api/documents/celery_tasks.py
- api/documents/libraries/process_document.py
This removes exception information from being sent back in a validation error.
> Remove sending back the exception data in the validation error

- api/letter_templates/templates/letter_templates/dbt_letter_base.html
- api/letter_templates/templates/letter_templates/ecju_base.html
- api/letter_templates/templates/letter_templates/nlr.html
- api/letter_templates/templates/letter_templates/siel.html
- pii-secret-exclude.txt
This PR changes references to "Department for International Trade" and "DIT" to "Department for Business and Trade" and "DBT" respectively in the following places in the caseworker application:
- No licence required letter template
- Refusal letter template
- SIEL template
- Inform letter template
Please also see the companion PR: https://github.com/uktrade/lite-frontend/pull/1834
I have also corrected any errors that stood out to me as unacceptable, these include:
- References to "Export Control Organisation" (should be "Export Control Joint Unit"). There are already references to Export Control Joint Unit in the letter so using Export Control Organisation is not only outdated it is confusing, hence including in this PR
- Using the old postcode (should be "SW1A 2DY")
More can be done to …
> LTD-3456 Update letter template name from DIT to DBT

- .circleci/config.yml
- Pipfile
- Pipfile.lock
- api/anonymised_db_dumps/tests/test_anonymised_dumps.py
- api/audit_trail/audit_trail_anonymisers.py
- api/audit_trail/tests/test_audit_trail_anonymisers.py
- api/cases/tests/factories.py
- api/conf/anonymise_model_config.yaml
- api/goods/goods_anonymisers.py
- api/goods/tests/test_goods_anonymisers.py
This change tightens up the anonymisation rules applied when creating anonymised DB dumps for lite-api.
Various fields (potentially) containing PII have been added to the anonymisation configuration.  Also the tests which prove that the anonymiser management command works (and follows our rules) have been improved so that they load the anonymised dump back in to the test database.  Previously, these test would assert that specific strings were not present in the created dump SQL string at all - now they assert that they are not present in the specific DB records that were anonymised.  This makes the tests much tighter.
**TODO:** point at latest `main` commit for django_db_anonymiser after companion PR merged; https://github.com/uktrade/django-db-anonymiser/pull/2
> [LTD-4710] Improve lite-api anonymisation

- api/applications/creators.py
- api/applications/tests/test_standard_application_submit.py
As lite-content is being deprecated, instead of updating the strings there, it was decided to update the places where those strings are used with updated string literals instead. The alternative is to update them in lite-content and then update the sha to point to an updated lite-content, which we want to avoid if possible.
[LTD-4766](https://uktrade.atlassian.net/browse/LTD-4766)
[LTD-4766]: https://uktrade.atlassian.net/browse/LTD-4766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4766 Change ultimate recipient to ultimate end-user

- api/applications/helpers.py
- api/applications/libraries/get_applications.py
- api/applications/managers.py
- api/applications/models.py
- api/applications/serializers/f680.py
These changes make it so that the case details page will be able to show F680 cases without errors.
The code is very much not DRY - `F680ApplicationViewSerializer` has a lot of overlap with `StandardApplicationViewSerializer`.  However this is something that we can look to tackle properly when working on F680s for real.
> [F680] F680 caseworker fixes

- api/audit_trail/streams/service.py
- api/audit_trail/tests/test_streams.py
This test started breaking after we moved to BST. 
From what I can tell we pass back next_time stamp 
https://github.com/uktrade/lite-api/blob/dev/api/audit_trail/streams/service.py#L192C63-L192C78
This appears to be sequence of events 
1) created_at in  UTC 
2) time.mktime(last_created_at.timetuple()) which was doing created_at -1 to make BST 
3) timezone.make_aware(datetime.fromtimestamp(timestamp) which was doing another -1 to make timezone suitable resulting in -2 hours. 
from what I can tell datetime.fromtimestamp was alway timezone aware since it depends on django settings however  time.mktime is timezone aware on circle CI but not in docker since it depends on TZ settings and this being picked up correctly. 
time.daylight = 1 on circle-ci and  time.daylight = 0 on docker both TZ is …
> LTD-4890-fix-broken-timestamp

- api/applications/creators.py
- api/applications/tests/test_standard_application_submit.py
- test_helpers/clients.py
Recently we updated the logic that shows "Ultimate end-user" information in the "Check your answers" page to also look at the `is_onward_incorporated` field of a good on application. This check was missing from the application creation logic in `creators.py` so it makes sense to update this also to use that field in the same way.
[LTD-4879](https://uktrade.atlassian.net/browse/LTD-4879)
[LTD-4879]: https://uktrade.atlassian.net/browse/LTD-4879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4879 Update api to check is_onward_incorporated on application creation

- api/cases/tests/test_good_precedents_view.py
- api/cases/views/views.py
The endpoint that returns goods precedents using a default page_size of 25. In case of applications that has more goods than this size then only 25 of them are populated with previous assessments.
Increase this to 200 to cover more number of products.
[LTD-4887](https://uktrade.atlassian.net/browse/LTD-4887)
[LTD-4887]: https://uktrade.atlassian.net/browse/LTD-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4887: Update page size to have precedents populated for all products

- api/applications/serializers/advice.py
- api/cases/models.py
- api/cases/tests/test_create_advice.py
- api/cases/tests/test_view_advice.py
This ensures that a team is saved against all advice objects even when not explicitly.
There will be a follow up to migrate all existing objects to have a team.
[LTD-4894](https://uktrade.atlassian.net/browse/LTD-4894)
[LTD-4894]: https://uktrade.atlassian.net/browse/LTD-4894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 4894 save team on advice objects

- api/letter_templates/context_generator.py
- api/letter_templates/tests/test_context_generation.py
This change fixes an issue where a re-opened application could not be submitted.
The issue manifests in the following situation;
- The case has two GoodOnApplication objects pointing to the same Good.
- The case has had final advice.
- The application is re-opened for editing.
- One of the GoodOnApplication records has been removed.
This would result in an IndexError at the point of generating the application document during submission.
This change fixes the issue by skipping any final advice where a matching GoodOnApplication cannot be found.
[LTD-4893](https://uktrade.atlassian.net/browse/LTD-4893)
[LTD-4893]: https://uktrade.atlassian.net/browse/LTD-4893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4893] Fix bug relating to submission of re-opened applications

- api/external_data/serializers.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
This is to remove the old denial csv file serializer which is no longer needed now that lite-routing has been updated with correct test data. The lite-routing sha update is also included in this PR.
> LTD-4937 Update denial csv file serializers to remove temp code

- api/external_data/serializers.py
- api/external_data/tests/denial_valid.csv
- api/external_data/tests/test_views.py
The example csv used in lite-frontend was updated to have 3 extra columns and also to reorder the columns (https://github.com/uktrade/lite-frontend/pull/1907) so this just does the same for the test csv file used in lite-api.
EDIT: As `consignee_name` as a column is not needed it has been removed from the example csv, and so a lot of the changes in this PR are now to keep things consistent now that this field is not expected to be used.
[LTD-4950](https://uktrade.atlassian.net/browse/LTD-4950)
[LTD-4950]: https://uktrade.atlassian.net/browse/LTD-4950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4950 Update lite-api test csv files to match example csv

- api/applications/tests/test_matching_denials.py
- api/data_workspace/tests/test_external_data_views.py
- api/external_data/documents.py
- api/external_data/management/commands/ingest_denials.py
- api/external_data/management/commands/tests/test_ingest_denials.py
- api/external_data/serializers.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
https://uktrade.atlassian.net/browse/LTD-4933
Changes denial search to use new fields from Denial Table 
Also the serialiser which is used to View on the UI and update on the UI has been updated to use the fields from Denial rather then Denial Entity. 
I've had to go alot further in this PR then I would expected.  The CSV loader and ingest_denials breaks as we change the default entity serializer as it become ready_only. This is deliberately done like this so we don't break the UI and require further changes. 
- We have already ingested a clean set of DenialEntity Objects that were release last week. Which fixed all the duplicates. 
- This PR deals with copying them across to Denial Model  through we are certain there's no duplicates (confirmed by testing locally)
- Wrapped in a …
> LTD-4933-es-search-model-changes

- api/cases/models.py
- api/cases/tests/test_edit_advice.py
Fixes an issue whereby a user could change team and then give advice and their previous advice would be removed.
This is because the code views this as an "edit" but instead we should take into account the users team as well and only "edit" in the case where the user and the team match.
[LTD-4900](https://uktrade.atlassian.net/browse/LTD-4900)
[LTD-4900]: https://uktrade.atlassian.net/browse/LTD-4900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ensure team is taken into account when filtering user advice

- api/search/product/documents.py
- api/search/product/tests/test_views.py
Currently part number search in products uses a delimiter '-' when analyzing the search string. Because of this if a part number contains hyphens then it splits into multiple tokens and matches on individual tokens as well. This can bring multiple results and not possible to get an exact match.
Users are expecting for an exact match so consider the whole search string without using any delimiters.
[LTD-5003](https://uktrade.atlassian.net/browse/LTD-5003)
[LTD-5003]: https://uktrade.atlassian.net/browse/LTD-5003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5003: Update part number search to look for exact matches

- api/core/search/filter_backends.py
- api/core/search/query_backends.py
- api/core/search/validators.py
- api/external_data/documents.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
- api/search/product/views.py
https://uktrade.atlassian.net/browse/LTD-5012)
This fundamentally changes how we search denials it allows more complex queries which can be customised by the user. 
To validate the default results UAT vs Test Env will use the same data and compare old vs new search/ This will allow us to validate this is sensible to roll out. 
Also dependant on UI PR
https://github.com/uktrade/lite-frontend/pull/1975
> LTD-5012-complex-denial-searching 

- api/applications/tests/factories.py
This is adding new factories to API to reduce coupling between dependant Repos. 
i.e lite_routing hence this will allow basic model changes without impacting these repos test data.
> denial-on-application-factories

- api/conf/settings.py
This is something small I noticed while doing the spike for LTD-4996. Currently the if-statement doesn't use the bool created in the line above, but it uses a string literal, which will always be true, so I guess this was just a typo.
[LTD-4996](https://uktrade.atlassian.net/browse/LTD-4996)
[LTD-4996]: https://uktrade.atlassian.net/browse/LTD-4996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix env variable usage in settings

- api/applications/serializers/denial.py
- api/applications/tests/test_matching_denials.py
- api/applications/views/denials.py
- api/data_workspace/tests/test_application_views.py
This code was added to allow the FE to be updated independently to the model changes.  
Once this PR is merged this code is no longer required. 
https://github.com/uktrade/lite-frontend/pull/1994
> LTD-4940-remove-backward-compatablity 

- api/external_data/documents.py
- api/external_data/tests/test_views.py
Remove commas in search queries which prevent matches being returned and remove highlighting on stop words.
[LTD-5041](https://uktrade.atlassian.net/browse/LTD-5041)
[LTD-5014](https://uktrade.atlassian.net/browse/LTD-5014)
[LTD-5041]: https://uktrade.atlassian.net/browse/LTD-5041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-5014]: https://uktrade.atlassian.net/browse/LTD-5014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5041 and LTD-5014 changes to address analyzer in denials search

- api/applications/libraries/get_applications.py
- api/applications/models.py
- api/applications/serializers/good.py
- api/applications/tests/test_audit_trail.py
Stops audit entries that are related to a `GoodOnApplication` from being removed when a `GoodOnApplication` object is deleted.
> Remove relation

- api/applications/tests/test_matching_denials.py
- api/core/search/filter_backends.py
- api/core/search/validators.py
- api/external_data/tests/denial_valid.csv
- api/external_data/tests/test_views.py
- api/search/product/tests/test_helpers.py
- api/search/product/tests/test_views.py
https://uktrade.atlassian.net/browse/LTD-5071
This has been tested on the case highlighted in the Jira and can confirm we can now match cases when we have a forward slash in the search parameters.
Originally this was in a frontend PR to test it quickly but that felt a bit hackey hence why it's been implemented as a backend change.
> LTD-5071-forward-slash-breaking-search

- api/goods/enums.py
- api/goods/serializers.py
- api/goods/tests/test_edit.py
- api/goods/tests/test_views.py
- api/goods/urls.py
- api/goods/views.py
Exporter has a choice to archive/restore a good and this is only allowed for goods that are submitted/verified on an application.
However we have a restriction that goods cannot be edited once they are submitted on an application. Removing this restriction can cause various issues so to avoid this add a dedicated endpoint which only allows archiving/restoring a particular good.
Add tests to ensure that only archive status can be updated using this endpoint.
> LTD-5154: Add dedicated endpoint to archive/restore a good

- .circleci/config.yml
- .coveragerc
- scripts/tests/test_which_frontend_branch.py
- scripts/which_frontend_branch.py
This aims to more intelligently pick the correct frontend branch to run the e2e tests against.
When we make an API change we kick off a set of e2e tests that checkout the specific API sha for that change, however the e2e tests would just checkout the default branch, which in our case was always `dev`.
In some cases the `dev` branch would be wrong as there would be a backward compatibility issue and the e2e tests would fail even though they shouldn't.
This script aims to pick the correct frontend branch to test against instead.
> Add a script to intelligently pick frontend branch

- api/goods/tests/test_goods_documents.py
- api/goods/views.py
(slight rewording by @hnryjmes)
Currently, when a document for a good has been uploaded and the application is in draft status, the exporter is able to download and view the document. However once the application has been submitted, the good is also marked as submitted. So when the exporter goes into the product list they're unable to download and view the document. 
This PR shows that the issue can be resolved using the current API calls by removing the check for the draft status. However this would leave just a single check on that view which is that the good organisation id is equal to the request user organisation id.
Given that this check was there before we should be confident that removing the draft status check is safe, or if not, consider an alternative approach here like writing …
> Allow good document stream for non draft statuses

- api/applications/models.py
- api/applications/tests/test_models.py
- api/applications/views/tests/test_amendments.py
- api/staticdata/statuses/enums.py
- api/staticdata/statuses/migrations/0014_rename_superseded_by_amendment_status.py
- api/staticdata/statuses/migrations/0015_rename_superseded_by_amendment_status.py
- api/staticdata/statuses/migrations/tests/test_0014_rename_superseded_by_amendment_status.py
- api/staticdata/statuses/migrations/tests/test_0015_rename_superseded_by_amendment_status.py
This change renames the status "Superseded by amendment" to "Superseded by exporter edit" as per the Jira.  This is for the purpose of better explaining things to users.
[LTD-5121](https://uktrade.atlassian.net/browse/LTD-5121)
[LTD-5121]: https://uktrade.atlassian.net/browse/LTD-5121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5121] Rename superseded by amendment status

- api/applications/models.py
- api/applications/tests/test_models.py
- api/parties/models.py
- api/parties/tests/test_models.py
The various model clone methods are currently used in the "amend by copy" feature.  Amend by copy ensures that when a user makes a major amendment to an application a new copy of an application is created and the original application put in to a superseded state.  We need to ensure that the application itself is copied and all related model records are also copied such that no records are re-used between the amendment application and the superseded application (with the exception of `Good` - which is used across multiple different applications).
To keep in line with this thinking, we need to also ensure that the new application has a full copy of any related `Party` records.
This change ensures that the `PartyOnApplication.clone()` method will associate the cloned PartyOnApplication …
> [LTD-5152] Ensure that PartyOnApplication.clone creates a copy of the related Party

- api/applications/views/amendments.py
- api/applications/views/tests/test_amendments.py
- api/core/decorators.py
- api/core/tests/test_decorators.py
- api/licences/managers.py
- api/licences/tests/test_managers.py
- api/staticdata/statuses/enums.py
This change adds validation to the new "create amendment" endpoint to ensure the following;
- The application to be amended is in a status that allows major edits to be invoked.
- The application to be amended has no non-draft Licence records associated to it.  If there exists an issued/cancelled/revoked/... licence for this application, the API endpoint responds with a 400 and does not allow the user to proceed.  We are anticipating that this will be quite rare and for now we will handle amending of applications which have licences by some other means.
[LTD-5078](https://uktrade.atlassian.net/browse/LTD-5078)
[LTD-5078]: https://uktrade.atlassian.net/browse/LTD-5078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5078] Amend by copy validation

- api/staticdata/management/commands/tests/test_commands.py
We are currently in the process of changing CLEs in LITE including adding many new CLEs. To do this we need to write migrations that create ControlListEntry objects in lite-api for each CLE. Previously we decided that any new migrations affecting routing should be written in the lite-routing repo and not in lite-api.
There is an existing seeding test in lite-api that checks the count of CLEs is as expected. Although this was written to ensure the seeding command was successful, it has been changed many times as new CLEs have been added through migrations. It is now just checking the count of CLEs is a particular number but this is not related to the count of CLEs added through the seeding command.
After discussion it was suggested that we probably don't want this test anymore, as it's not …
> Remove lite-api test for expected count of CLEs

- api/applications/models.py
- api/applications/tests/test_models.py
- api/documents/models.py
- api/parties/models.py
- api/parties/tests/test_models.py
This PR ensures that documents are cloned appropriately during the "amend by copy" flow.
In particular this;
- Ensures that `PartyDocument` records are copied instead of shared between cloned `Party` records.
- Ensures that `ApplicationDocument` records are also cloned when an application is cloned.  This will cover firearm dealer certificates, section 5 certificates, supporting documents etc.
[LTD-5105](https://uktrade.atlassian.net/browse/LTD-5105)
[LTD-5105]: https://uktrade.atlassian.net/browse/LTD-5105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5105] Amend by copy document copying

- api/applications/managers.py
- api/applications/tests/test_view_application.py
https://uktrade.atlassian.net/browse/LTD-5223
Removes the `finalised` applications from the `submitted` tab.
> LTD-5223-tab-finalised

- api/licences/serializers/view_licence.py
- api/licences/tests/test_get_licences.py
- api/licences/urls.py
- api/licences/views/main.py
https://uktrade.atlassian.net/browse/LTD-5247
This is to support the new feature of allowing License(s) to be updated directly from the UI. 
This is adding a new endpoint to allow govuser to retrieval the details  of a License based on id.  New Serialiser is used since it's very light weight. 
Also We will leverage this end point to allow updates to an individual License. 
Hence this will be followed by a series of PRs
> LTD-5247-new-endpoint-view-license 

- api/applications/serializers/good.py
- api/applications/tests/test_edit_good_on_applications.py
- api/applications/urls.py
- api/exporter/applications/permissions.py
- api/exporter/applications/views.py
Add exporter specific endpoint to allow editing of quantity/value of goods added to an application.
This endpoint is restrictive and only quantity, value can be edited.
As we are moving towards separating exporter, caseworker urls a new directory is created with the intention of grouping
relevant views under that directory.
Permission checks are moved to their own custom permission classes.
Note: This ticket is mainly about auditing quantity and value changes but this PR doesn't add audit events.
Editing of quantity value was introduced as a minor edit earlier but now we have removed minor edits completely. To perform major edits application need to be in `draft` state at which point it is not associated to any `Case`. This is a problem for audit events because they are always associated …
> LTD-5083: Add endpoint to allow update of quantity value fields only

- api/applications/serializers/generic_application.py
- api/applications/tests/test_view_application.py
On the exporter dashboard, for archived applications we want to show 'Submitted by' column but that data is not sent atm.
Update serializer to provide this field.
Relevant FE PR: https://github.com/uktrade/lite-frontend/pull/2102
[LTD-5287](https://uktrade.atlassian.net/browse/LTD-5287)
[LTD-5287]: https://uktrade.atlassian.net/browse/LTD-5287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5287: Include submitted_by in the application data sent to exporter

- api/applications/serializers/standard_application.py
- api/data_workspace/v1/tests/test_applications_views.py
Ensure that `amendment_of` and `superseded_by` are exposed to data workspace via our existing "standard applications" DW endpoint.
This PR additionally makes the tests for this endpoint tighter by asserting the whole response is as expected.
[LTD-5318](https://uktrade.atlassian.net/browse/LTD-)
[LTD-5318]: https://uktrade.atlassian.net/browse/LTD-5318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5318] Expose superseded_by and amendment_of to data workspace

- api/applications/caseworker/permissions.py
- api/applications/caseworker/tests/test_permissions.py
This change ensures that caseworkers are unable to set the case status to "Superseded by exporter edit" via the API.
[LTD-5299](https://uktrade.atlassian.net/browse/LTD-5299)
[LTD-5299]: https://uktrade.atlassian.net/browse/LTD-5299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5299] Prevent caseworkers setting superseded status

- api/organisations/serializers.py
- api/organisations/tests/test_documents.py
Exporter had issue whereby on Organisation Details page if they updated their 'Registered firearms dealer' certificate the details didn't update to the new certificate.
This issue only occurred if they updated their certificate to one that had an expiry date earlier than their current certificate.  If their new cert had an expiry date in the future the issue did not occur.
I found that even though the documents were being saved correctly the `OrganisationDetailSerializer` was presenting the org details view with the documents listed in order of `expiry_date` instead of `created_by`.  Changing to order by `created_by` repaired the issue on the frontend as the logic is there which presents the documents correctly.
[LTD-5341](https://uktrade.atlassian.net/browse/LTD-5341)
[LTD-5341]: …
> LTD-5341 Update Firearms Cert on Org Details Page issue

- api/applications/tests/factories.py
- api/support/management/commands/remove_case_final_advice.py
- api/support/management/commands/tests/test_remove_case_final_advice.py
A new management command which allows all finial advice to be deleted. 
This is required when TAU change their minds and have issue various final advice on a case. We need to invalidate this so the case can go back to post-circulation
> LTD-5304-managment-cmd-remove-advice 

- .circleci/config.yml
- api/applications/exceptions.py
- api/applications/models.py
- api/applications/tests/test_models.py
- pytest.ini
This stops a race condition where an amendment request hits our API multiple times simultaneously.
It's possible for a user to have submitted the "confirm major edit" action multiple times and we want to ensure that the request is only processed once.
To handle this we ensure that a lock is put on the application object and then check the status of the application after any simultaneous edits are being made.
To properly test this I've added a separate CI job due to this test needing to use `TransactionTestCase` and that not playing nicely with other tests.
[LTD-5392](https://uktrade.atlassian.net/browse/LTD-5392)
[LTD-5392]: https://uktrade.atlassian.net/browse/LTD-5392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix a race condition when multiple amendments are made

- .circleci/config.yml
The migrations tests have now become the longest running part of our API CI suite.
Running these in parallel now reduces the total time spent running.
> Add parallelism to migration tests

- api/cases/notify.py
- api/cases/tests/test_notify.py
- gov_notify/payloads.py
- gov_notify/tests/test_payloads.py
When looking to update the URLs for the public beta switch over it was hard to decipher what was a used template variable and/or a used template. This should remove both templates and template variables that aren’t being used.
[LTD-5424](https://uktrade.atlassian.net/browse/LTD-5424)
[LTD-5424]: https://uktrade.atlassian.net/browse/LTD-5424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 5424 tidy up email payloads

- api/data_workspace/v1/licence_views.py
- api/data_workspace/v1/serializers.py
- api/data_workspace/v1/tests/test_licence_views.py
- api/data_workspace/v1/tests/test_serializers.py
- api/licences/serializers/view_licence.py
- api/licences/tests/test_get_licences.py
- api/licences/views/main.py
Fix licence list page when a good has been used multiple times on an application.
The issue was around advice objects being generated multiple times for the same good and one of the serializers falling over as a result.
The serializer for this page actually didn't need to load the advice at all so I've created a separate serializer that just sends what's required for the licence list page.
I've also separated out the Data Workspace serializer as well as this was also loading up information that it didn't need to.
[LTD-5378](https://uktrade.atlassian.net/browse/LTD-5378)
[LTD-5378]: https://uktrade.atlassian.net/browse/LTD-5378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 5378 licence list bug

- api/licences/serializers/view_licence.py
- api/licences/tests/test_get_licence.py
- api/licences/views/main.py
This creates a separate serializer for the exporter licence detail endpoint. This stops an issue with the original `get_advice` method that would fail given more than one advice object for a good on a licence.
Having an independent serializer here means that we are only sending the relevant and required information for the view on the frontend that doesn't require advice.
[LTD-5454](https://uktrade.atlassian.net/browse/LTD-5454)
[LTD-5454]: https://uktrade.atlassian.net/browse/LTD-5454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add separate serializer for exporter licence details

- .circleci/config.yml
This change adds a new circle CI job to ensure that the lite_routing documentation is up to date.
This is achieved by generating the docs again in circleci (after bringing up a seeded/migrated app) and checking for differences from what we have in git for lite-routing.
If differences are observed, the check fails with an error message which shows the diff.
PRs for the lite-routing repository will get this check "for free" since the CI for that repository calls through to lite-api's CI pipeline.
**NOTE:** We should only merge this PR when the companion PR in lite-routing has merged https://github.com/uktrade/lite-routing/pull/268 AND when we are ready to update the lite-routing submodule sha.
[LTD-5428](https://uktrade.atlassian.net/browse/LTD-5428)
[LTD-5428]: …
> [LTD-5428] Make CI check routing docs are up to date

- api/documents/libraries/tests/test_s3_operations.py
- api/documents/models.py
- api/documents/tests/factories.py
- api/documents/tests/test_document_model.py
- test_helpers/s3.py
Stop a file from being deleted from S3 if the file is also pointed to by another `Document` object.
The only case where this won't happen is if a file is found to be unsafe and in that case we still remove the file.
[LTD-5467](https://uktrade.atlassian.net/browse/LTD-5467)
[LTD-5467]: https://uktrade.atlassian.net/browse/LTD-5467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Don't delete a file that is shared across multiple documents

- .circleci/config.yml
Removing this redundant top level job from the circleci config should fix an incompatibility which lite-routing has calling circleci on lite-api.
> Remove routing docs checking job from circleci config

- .circleci/config.yml
This makes sure that the correct code is checked out when running code coverage.
When running our tests it's possible that the testing job checked out a different submodule e.g. because it's testing a specific branch of lite_routing, than what is checked out when `check_coverage` runs.
When the above happens this leads to an error in coverage because it's trying to find a code file to use to display code coverage which may not actually exist.
To resolve this we make sure that the same procedure to check out the relevant submodules is used across both the testing and code coverage jobs.
[LTD-5482](https://uktrade.atlassian.net/browse/LTD-5482)
[LTD-5482]: https://uktrade.atlassian.net/browse/LTD-5482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> Ensure coverage checks out correct routing submodule

- api/letter_templates/templates/letter_templates/refusal.html
- api/letter_templates/templates/letter_templates/siel.html
- api/letter_templates/templatetags/custom_tags.py
- api/letter_templates/tests/test_letter_templates.py
Split good name onto different lines on Licence pdf by comma to ensure full good details appear on licence pdf.
Investigated and there are 2727 out of 14574 good records which contain commas so this a lighter touch on the existing data than adding splitting across any character types although this could be introduced.
[LTD-5537](https://uktrade.atlassian.net/browse/LTD-5537)
[LTD-5537]: https://uktrade.atlassian.net/browse/LTD-5537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5537-Licence-document-cutting-off-details

- api/cases/tests/test_rerun_routing_rules.py
- test_helpers/clients.py
Temporarily skip rerun routing rules test.
I'm stuck in a bit of a chicken and egg situation where this rerun routing rule test is becoming very difficult to maintain in a backward compatible way.
However, this is only a problem for the tests and not a problem in reality due to the fact that I have a fix for this that will go with the sha update that matches against lite-routing.
Given that this is just a testing problem, it's temporary and it's also in an area of the code that we've "turned off" I've taken the decision that skipping this test is the most sensible option.
[LTD-5521](https://uktrade.atlassian.net/browse/LTD-5521)
[LTD-5521]: https://uktrade.atlassian.net/browse/LTD-5521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Temporarily skip rerun routing rules test

- api/organisations/caseworker/views/tests/test_users.py
- api/users/tests/factories.py
- test_helpers/clients.py
- test_helpers/faker.py
- test_helpers/helpers.py
Ensure a unique email address is used across all tests.
This should stop tests failing on an intermittent `IntegrityError`.
> Set unique email address for base user

- api/conf/settings.py
This adds a setting that will be used by the generate rules documents management command.
[LTD-5521](https://uktrade.atlassian.net/browse/LTD-5521)
[LTD-5521]: https://uktrade.atlassian.net/browse/LTD-5521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add setting for routing documents location

- api/workflow/routing_rules/models.py
- api/workflow/routing_rules/tests/test_models.py
Remove unused model method to run criteria function now routing rules are no longer DB driven.
[LTD-5598](https://uktrade.atlassian.net/browse/LTD-5598)
[LTD-5598]: https://uktrade.atlassian.net/browse/LTD-5598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove unused model criteria function method

- api/applications/management/commands/update_party_address.py
- api/applications/management/commands/update_party_name.py
- api/applications/tests/test_update_parties_address.py
- api/applications/tests/test_update_party_name.py
When saving and extra backslash is added to carriage returns which are common in these variables.  This fixes an issue whereby these commands took account of this on the old variable to be changed but not the new variable being introduced.
[LTD-5623](https://uktrade.atlassian.net/browse/LTD-5623)
[LTD-5623]: https://uktrade.atlassian.net/browse/LTD-5623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 5637 fix csv save extra backslash

- .circleci/config.yml
Coverage has released a new version today and it's causing our `check_coverage` job to fail on CircleCI.  If we use the `config.yml `to get it to specifically install the latest working version from yesterday (7.6.4) and the jobs work okay.
[LTD-5647](https://uktrade.atlassian.net/browse/LTD-5647)
[LTD-5647]: https://uktrade.atlassian.net/browse/LTD-5647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Code coverage change on CircleCI

- api/data_workspace/v2/serializers.py
- api/data_workspace/v2/tests/bdd/licences/conftest.py
- api/data_workspace/v2/tests/bdd/licences/test_destinations.py
- api/data_workspace/v2/tests/bdd/scenarios/destinations.feature
- api/data_workspace/v2/urls.py
- api/data_workspace/v2/views.py
The basic test is for the response data from the endpoint being in the right format as expected. There is another test for deleting a party. When a case is in non-draft state, deleting a party uses a different `.delete()` method which actually does not delete the record, but instead sets a `deleted_at` field with the current datetime. It is important that these "deleted" parties do not appear as destinations in the published data so the test checks they are not included.
[LTD-5650](https://uktrade.atlassian.net/browse/LTD-5650)
[LTD-5650]: https://uktrade.atlassian.net/browse/LTD-5650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add destination endpoint

- .copilot/phases/pre_build.sh
HOT Fix for dbt-platform endesive not installed
this is required for UAT testing on PROD DBT Platform. 
This has been tested on DBT and will be tested by deployed to Support. 
No Gov-paas release is required as it has no impact..
> hot-fix-dbt-endesive

- api/conf/pagination.py
- api/data_workspace/v1/good_views.py
This is to ensure consistent results across pages
Currently it's possible that duplicates can occur as the order of the queryset isn't deterministic
[LTD-5718](https://uktrade.atlassian.net/browse/LTD-5718)
[LTD-5718]: https://uktrade.atlassian.net/browse/LTD-5718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use cursor pagination for goods endpoint

- api/data_workspace/v2/tests/bdd/conftest.py
Current code sorting the results based on first key in the results but for one of the test this is same for all rows so randomly it sorts by different order and causing the test to fail. Update the test to sort by all keys so we have a consistent order.
> LTD: Fix sorting issue

- api/organisations/serializers.py
- api/organisations/tests/test_organisations.py
Remove validation agains a rejected CRN when and exporter registers.
as per ticket: 'The change here is to only validate against CRNs where the registration that are either pending or approved.'
[LTD-5760](https://uktrade.atlassian.net/browse/LTD-5760)
[LTD-5760]: https://uktrade.atlassian.net/browse/LTD-5760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5760 remove CRN check against rejected organisations

- api/applications/creators.py
Uses existing validation functions to make `end_user` and product/goods section of application required by api.  This passes validation error to frontend to be presented to the user.
[LTD-5801](https://uktrade.atlassian.net/browse/LTD-5801)
[LTD-5801]: https://uktrade.atlassian.net/browse/LTD-5801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5801 Make product and end user sections required

- test_helpers/clients.py
When creating a standard application in tests, by default, a good will be generated for you.
In some cases this isn't the desired behaviour and this allows it to be toggled accordingly.
> Allow good creation to be skipped when creating a test application

- api/applications/exporter/serializers.py
- api/applications/exporter/urls.py
- api/applications/exporter/views/applications.py
- api/applications/exporter/views/mixins.py
- api/applications/exporter/views/tests/test_applications.py
https://uktrade.atlassian.net/browse/LTD-5817
The exporter case view is being changed to include the application history. 
Rather then expand and over whelm existing 'LARGE' views and endpoints a new endpoint has been created just to extract application history. This uses the new exporter API pattern. 
The history for each application within an amendment is expected to show the full history showing the latest at the top. Hence the data is the same regardless of which case is queried. The UI will remove the hyperlink for the case that's currently being viewed. 
Frontend PR 
https://github.com/uktrade/lite-frontend/pull/2343
> LTD-5833-application-history-endpoint 

- api/data_workspace/metadata/routers.py
The table metadata endpoint wasn't checking HAWK authentication.
This makes that happen.
[LTD-5875](https://uktrade.atlassian.net/browse/LTD-5875)
[LTD-5875]: https://uktrade.atlassian.net/browse/LTD-5875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add hawk authentication to table metadata endpoint

- api/data_workspace/urls.py
- api/data_workspace/v0/urls.py
- api/data_workspace/v1/audit_views.py
- api/data_workspace/v1/urls.py
- api/data_workspace/v2/urls.py
This makes the audit move case endpoint more efficient.
There's quite a lengthy comment in the code as to why I'm doing it like this but essentially this is the quickest route to getting this endpoint efficient and we can spend more time in the future making it work with the new CaseQueueMovement table.
[LTD-5887](https://uktrade.atlassian.net/browse/LTD-5887)
[LTD-5887]: https://uktrade.atlassian.net/browse/LTD-5887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make audit move pipeline more efficient

- api/f680/caseworker/serializers.py
- api/f680/exporter/filters.py
- api/f680/exporter/tests/test_views.py
- api/f680/exporter/urls.py
- api/f680/exporter/views.py
- api/f680/models.py
- api/f680/tests/test_models.py
Add the capability for an exporter to submit an F680 application.
This PR also makes the exporter F680 endpoints only operate on draft applications, to avoid any chance of an exporter making an edit to a submitted application.
[LTD-5908](https://uktrade.atlassian.net/browse/LTD-5908)
[LTD-5908]: https://uktrade.atlassian.net/browse/LTD-5908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5908] Submit F680 application

- Dockerfile.opensearch-dashboards
- docker-compose.yml
- opensearch_dashboards.yml
Add opensearch dashboards as a developer tool to be able to view and test indexed data locally.
> Add opensearch dashboards as a developer tool

- api/cases/application_manifest.py
- api/cases/enums.py
- api/cases/generated_documents/helpers.py
- api/cases/generated_documents/tests/test_helpers.py
- api/cases/tests/test_application_manifest.py
- api/letter_templates/context_generator.py
- api/letter_templates/templates/letter_templates/f680_approval.html
- api/letter_templates/tests/test_context_generation.py
This change ensures that we are able to generate an approval document for F680s.
- The approval document generation endpoint assumed that approval documents would have a draft licence.  As far as we know, we will not have a licence object for F680s so this has been made conditional with a new `get_feature()` method on the application manifest.
- The template for the F680 approval document was also enhanced so that we show more application details.
[LTD-5946](https://uktrade.atlassian.net/browse/LTD-5946)
[LTD-5946]: https://uktrade.atlassian.net/browse/LTD-5946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5946] F680 generate approval document

- api/staticdata/upload_document_for_tests/views.py
When in debug mode, if there is a file upload issue then raise the exception.
This should make it easier to debug exactly what failed when an upload error occurs, especially when running e2e tests in CI.
> Raise exception if in debug mode when uploading documents in tests

- api/cases/enums.py
- api/cases/tests/factories.py
- api/cases/tests/test_enums.py
Get the case type identifier from the specific enum class from the case type object.
This is in preparation for routing changes where routing rules can be defined at different levels of the case type hierarchy.
[LTD-5979](https://uktrade.atlassian.net/browse/LTD-5979)
[LTD-5979]: https://uktrade.atlassian.net/browse/LTD-5979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Get the relevant case type value for an enum type

- api/cases/tests/test_get_case.py
- api/f680/caseworker/serializers.py
- api/f680/managers.py
- api/f680/models.py
This change exposes SecurityReleaseRequest, Product and Recipient on the case detail API endpoint for F680 applications.
[LTD-5991](https://uktrade.atlassian.net/browse/LTD-5991)
[LTD-5991]: https://uktrade.atlassian.net/browse/LTD-5991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5991] Expose related F680 models on caseworker case detail endpoint

- api/f680/conftest.py
- api/f680/exporter/serializers.py
- api/f680/exporter/tests/test_views.py
- api/f680/exporter/views.py
- api/f680/models.py
- api/f680/tests/test_models.py
Change the F680 application JSON contract so that `fields` is a dictionary as opposed to an array.  This allows us to have a much easier time with DRF serializer validation and additionally makes lookups much easier.
Companion frontend PR: https://github.com/uktrade/lite-frontend/pull/2419
**NOTE** On merge we will need to delete existing F680 applications on dev2 as this contract change is backwards incompatible.  We could do a data migration, but since we only have test applications on a dev environment this would be overkill.
[LTD-5993](https://uktrade.atlassian.net/browse/LTD-5993)
[LTD-5993]: https://uktrade.atlassian.net/browse/LTD-5993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5993] Change F680 JSON contract for fields to be dict

- api/data_workspace/v1/views.py
Use cursor pagination for organisation and party endpoints to decrease the number of pipeline failures due to duplicate entries that are caused by non-deterministic results across pages.
[LTD-6042](https://uktrade.atlassian.net/browse/LTD-6042)
[LTD-6042]: https://uktrade.atlassian.net/browse/LTD-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating organisation and party DW endpoints to use cursor pagination

- api/applications/serializers/generic_application.py
- api/applications/serializers/standard_application.py
- api/applications/tests/test_create_application.py
- api/applications/views/applications.py
- api/conf/exporter_urls.py
- api/core/context_processors.py
- api/core/tests/test_viewsets.py
- api/core/viewsets.py
- api/export_licences/exporter/serializers.py
- api/export_licences/exporter/tests/test_views.py
- api/export_licences/exporter/urls.py
- api/export_licences/exporter/views.py
- api/f680/exporter/views.py
Add a new endpoint for creating export licence applications.
This is deprecating the other endpoint, which I've also made simpler, in this pull request.
The idea being that this is a backwards compatible change where I can create a new endpoint to make changes whilst still keeping the old one around.
There will be a later frontend PR that switched to this new endpoint.
[LTD-6028](https://uktrade.atlassian.net/browse/LTD-6028)
[LTD-6028]: https://uktrade.atlassian.net/browse/LTD-6028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Create new endpoint for export licence applications

- api/applications/management/commands/update_good_name.py
- api/applications/tests/test_update_good_name.py
resolved issue with escaping \
looked into adding the same to party name + address but they focus on newlines and removing the escaping causes issues there, lets revisit if we hit an issue with there being escaped characters there, perhaps a shared csv reader
[LTD-6048](https://uktrade.atlassian.net/browse/LTD-6048)
[LTD-6048]: https://uktrade.atlassian.net/browse/LTD-6048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fixed csv reader and the tests

- api/f680/exporter/serializers.py
- api/f680/exporter/tests/test_views.py
- api/f680/exporter/views.py
When selecting yes on declaration you get an error `{'errors': {'foi_reason': ['This field may not be blank.']}}` so set allowed_blank to True and now this error will not appear.
[LTD-6068](https://uktrade.atlassian.net/browse/LTD-6068)
[LTD-6068]: https://uktrade.atlassian.net/browse/LTD-6068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Bugfix] LTD-6068 allow foi_reason to be blank

- api/audit_trail/managers.py
- api/cases/views/search/service.py
The main issue here was that the original query was getting all of the activity updates, serializing them all and then chucking nearly all of the results away.
In testing there was a page that was serializing ~2000 activity updates and then pruning this down to ~50.
This does the pruning much earlier and thus only needs to serializer activities that it definitely needs.
[LTD-6176](https://uktrade.atlassian.net/browse/LTD-6176)
[LTD-6176]: https://uktrade.atlassian.net/browse/LTD-6176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Optimise fetching most recent two activities on queue view

- api/cases/models.py
- api/cases/tests/test_models.py
- api/data_workspace/v2/serializers.py
- api/data_workspace/v2/tests/bdd/conftest.py
- api/data_workspace/v2/tests/bdd/scenarios/licence_decisions.feature
- api/staticdata/statuses/factories.py
This fixes an issue where a user may click the "finalisation" stage multiple times and this was creating unnecessary duplicate objects as a result and affecting Official Statistics data.
This now puts in place a lock and an extra check to make sure that any extra clicks don't duplicate data.
[LTD-6102](https://uktrade.atlassian.net/browse/LTD-6102)
[LTD-6102]: https://uktrade.atlassian.net/browse/LTD-6102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Handle users clicking "finalise" multiple times

- api/f680/conftest.py
- api/f680/exporter/serializers.py
- api/f680/models.py
- api/f680/tests/test_models.py
This change ensures that `security_grading_other` is populated when an F680 application is submitted - if the corresponding field was present in application JSON.
[LTD-6055](https://uktrade.atlassian.net/browse/LTD-6055)
[LTD-6055]: https://uktrade.atlassian.net/browse/LTD-6055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-6055] Ensure security_grading_other populated on F680 application submission

- api/cases/tests/test_sla.py
- api/queries/end_user_advisories/tests/test_create_end_user_advisories.py
- api/queries/goods_query/tests/test_goods_queries.py
These tests start failing due to changes in the routing engine as it currently ignores anything that is either a Standard application or an F680 application
This prepares for routing changes that skip these application types
[LTD-6092](https://uktrade.atlassian.net/browse/LTD-6092)
[LTD-6092]: https://uktrade.atlassian.net/browse/LTD-6092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove, or skip, tests are no longer maintained

- api/queries/goods_query/tests/test_goods_queries.py
This was missed off of a previous commit that skipped a bunch of failing tests
These tests start failing due to changes in the routing engine as it currently ignores anything that is not either a Standard application or an F680 application
This prepares for routing changes that skip these applications type
[LTD-6092](https://uktrade.atlassian.net/browse/LTD-6092)
[LTD-6092]: https://uktrade.atlassian.net/browse/LTD-6092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove, or skip, tests that are no longer maintained

- api/cases/enums.py
- api/cases/views/search/service.py
For companion PR making sure users can filter by case type on the queue view.
[LTD-6160](https://uktrade.atlassian.net/browse/LTD-6160)
[LTD-6160]: https://uktrade.atlassian.net/browse/LTD-6160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-6160] Ensure search API GET endpoint returns only active case types

- api/f680/caseworker/tests/test_views.py
- api/f680/caseworker/views.py
In a previous PR I had changed the permissions but not re-implemented them correctly.  This PR corrects that and now enables users to view read only version of the case even if they can't make a recommendation on it.
[LTD-6228](https://uktrade.atlassian.net/browse/LTD-6228)
[LTD-6228]: https://uktrade.atlassian.net/browse/LTD-6228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6228 fix permission implementation to enable get request to view case detail

- api/applications/models.py
- api/applications/serializers/good.py
- api/applications/tests/test_adding_goods.py
- api/goods/serializers.py
For OIELs and our "single user journey" applications there will be no quantity nor value provided as part of the application process.
This loosens the requirements for these fields.
[LTD-6030](https://uktrade.atlassian.net/browse/LTD-6030)
[LTD-6030]: https://uktrade.atlassian.net/browse/LTD-6030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow quantity and value to be null when creating a good on application
