- applications/creators.py
- applications/views.py
> bug-fix-additional-documents

- .gitmodules
> Revert "Change submodule URL to HTTPS."

- applications/tests/tests_managing_countries_on_goods_type.py
I think this is the problem from https://code.djangoproject.com/ticket/26338.
> Fix applications.tests.tests_managing_countries_on_goods_type on postgres

- applications/tests/tests_adding_countries.py
- letter_templates/tests/tests_create.py
- letter_templates/tests/tests_edit.py
- letter_templates/tests/tests_view.py
- static/management/SeedCommand.py
- static/management/commands/coverage.py
- static/management/commands/seedall.py
- static/management/commands/seedcasestatuses.py
- static/management/commands/seedcontrollistentries.py
- static/management/commands/seedcountries.py
- static/management/commands/seeddenialreasons.py
- static/management/commands/seedgovusers.py
- static/management/commands/seedlayouts.py
- static/management/commands/seedorgusers.py
- static/management/commands/seedpermissions.py
- static/management/commands/seedsystemflags.py
- test_helpers/clients.py
This PR is to fix some duplication when seeding. Stop tests from running seeding per test and to make the console output easier to digest; the console ONLY displays entities created or updated
> enhance: Seeding & Testing

- .circleci/config.yml
This pull request introduces workflows for our CircleCI - this means that our tests and linting can run in parallel and they can also report separate statuses. No more having to dig in to CircleCI to see why your branch is red :)
> ci: Workflows

- gov_users/serializers.py
- organisations/serializers.py
- organisations/views/users.py
Minimise the amount of data being passed forward to the page, increasing the speed greatly. Deployed on QA.
> Bug: LT-2040 manage organisation (user) page performance

- cases/tests/tests_search_cases.py
- queries/end_user_advisories/tests/test_update_end_user_advisories.py
- static/statuses/enums.py
- added two additional states for goods queries - PV review and CLC review
https://uktrade.atlassian.net/browse/LT-2149
> feat: LT-2149 - Add PV Grading and CLC to list of available goods query states

- cases/tests/tests_sla.py
- flags/serializers.py
- flags/views.py
- teams/serializers.py
> bug: LT-2388 flags performance

- applications/serializers/generic_application.py
- applications/views/applications.py
- applications/views/external_locations.py
- applications/views/goods.py
- applications/views/parties.py
- applications/views/sites.py
- cases/generated_documents/views.py
- cases/libraries/delete_notifications.py
- cases/views/case_notes.py
- cases/views/views.py
- conf/authentication.py
- conf/decorators.py
- conf/middleware.py
- goods/libraries/get_goods.py
- goods/serializers.py
- goods/views.py
- licences/views.py
- organisations/libraries/get_organisation.py
- organisations/views/organisations.py
- organisations/views/roles.py
- queries/end_user_advisories/serializers.py
- queries/end_user_advisories/views.py
- queries/goods_query/serializers.py
- queries/goods_query/views.py
- test_helpers/test_endpoints/client.py
- users/libraries/notifications.py
- users/models.py
- users/views.py
Reduce the queries and performance impact of the authentication classes (particularly ExporterAuthentication)
Organisation is now only fetched when necessary
Shaves significant load time off each Exporter endpoint
> Performance: Authentication

- gov_users/serializers.py
- gov_users/views/roles_views.py
> Revert "performance: roles list"

- queues/service.py
- queues/tests/tests_endpoints_response_queues.py
- queues/tests/tests_performance.py
- queues/views/queues.py
- teams/tests/tests_endpoints_response_teams.py
- test_helpers/clients.py
> Bug: Lt-2590 - non-paginated queues list performance

- cases/managers.py
- cases/tests/tests_endpoints_response_cases.py
Cases being sorted by status has been removed from front-end functionality, so tidied up the backend to reflect these changes.
> Bug: LT-2565 - performance of sorted cases

- open_general_licences/serializers.py
- open_general_licences/tests/test_gets.py
- open_general_licences/views.py
- organisations/serializers.py
- organisations/tests/tests_sites.py
* Increased amount of information returned when getting a site's records
> feat: LT-1409 - OGL sites

- Pipfile
- Pipfile.lock
- cases/admin.py
- cases/tests/tests_is_recently_updated.py
- conf/authentication.py
- conf/settings.py
- conf/urls.py
- core/tests/test_views.py
- core/views.py
- letter_templates/helpers.py
- organisations/tests/tests_users.py
- static/control_list_entries/parser.py
- static/management/SeedCommand.py
- static/management/commands/seedall.py
- static/management/commands/seedcountries.py
- test_helpers/clients.py
- users/models.py
> Add staff SSO for django admin login + use django.conf.settings

- cases/managers.py
bug was different to as described in ticket. Was actually just ordering on the wrong field
> bug: SLA ordering

- api/conf/urls.py
- api/search/application/backends.py
- api/search/application/documents.py
- api/search/application/views.py
This PR contains remaining changes required as part of acceptance criteria mainly multi-keyword search and wildcard search.
Covers simple cases as with combinations it can get very complex.
- Multi-keyword search example
`ML1a,ML1b`
- Wildcard search examples
single character wildcard: `123?`
multi character wildcard: `7657*`, `spect*met*`
> LTD-152 Remaining changes 

- api/search/application/documents.py
- api/search/application/views.py
Searching by queue name and their team will be useful
> Search by Application queue name and team

- api/search/application/documents.py
- api/search/application/views.py
To be able to filter applications by Case officer
Add custom analyzer for email
> Search by case officer username and email

- api/reports/management/commands/reports.py
- api/reports/queries/standard.py
To act as a template for building reports that aggregate this raw data like
summary of SIELs
> LTD-215: Reporting - Add query for standard licences with goods and ratings

- api/reports/management/commands/reports.py
- api/reports/queries/standard.py
This report allows reporting on all changes made to licences/cases in a given
period related to the goods attached to those licences.
> LTD-210: Reporting - SQL for Goods amendments raw report

- api/conf/settings.py
- api/conf/urls.py
- api/data_workspace/admin.py
- api/data_workspace/apps.py
- api/data_workspace/tests.py
- api/data_workspace/urls.py
- api/data_workspace/views.py
- api/open_general_licences/tests/test_gets.py
- api/open_general_licences/urls.py
- api/open_general_licences/views.py
- Add new endpoint to expose Licences to Data workspace
- Results are paginated using `LimitOffsetPagination`
- OGL types endpoint updated to provide paginated results
> LTD-240: Expose Licences to Data workspace

- api/compliance/enums.py
- api/compliance/tests/test_visit_case.py
- api/letter_templates/layouts/ecju.html
- Fix context preparation that is used to generate documents
- Fix template also to display the values correctly
> LTD-264:  Cannot generate documents compliance cases

- docker-compose.yml
Environment variable format was incorrect for elasticsearch
> Docker-compose typo

- api/applications/serializers/good.py
- api/applications/tests/tests_adding_goods.py
- api/applications/views/goods.py
This extends the GoodOnApplicationCreateSerializer to support
year of manufacture
> Support Year of Manufacture as part of add preexisting good flow

- .circleci/config.yml
- Pipfile
- Pipfile.lock
Pinning to version 1.6.2 due to [an issue in 1.6.3](https://github.com/PyCQA/bandit/issues/657).
> Pin bandit version

- .bandit
- .coveragerc
- .prospector.yaml
- .pylintrc
- Pipfile
- Pipfile.lock
- api/conf/settings.py
- pyproject.toml
- vendor/separatedvaluesfield/__init__.py
- vendor/separatedvaluesfield/models.py
- vendor/separatedvaluesfield/tests/models.py
- vendor/separatedvaluesfield/tests/settings.py
- vendor/separatedvaluesfield/tests/tests.py
django-separatedvaluesfields lib requires changes in their current git HEAD that have not been released to pypi. CloudFoundry continues to reinstall the previous pypi package regardless of Pipfile’s use of a git URL, therefore the current version of the lib has been added to the project instead.
- adds `/vendor` to PATH in `settings.py`
- excludes `/vendor` from all linters
> Vendor django-separatedvaluesfields

- api/goods/helpers.py
- api/goods/migrations/0025_good_name.py
- api/goods/models.py
- api/goods/serializers.py
- api/goods/tests/tests_create.py
- api/goods/views.py
- api/search/application/documents.py
Add new mandatory field `name` to `Good` model and updated tests.
> LTD-285: Add product name api changes

- .circleci/config.yml
- api/conf/settings.py
since we already have codeclimate on this repo, try to enable codeclimate coverage features
> Enable coverage reports to codeclimate

- api/cases/views/search/service.py
This query was slowing down as the number of flags increased in the system. The
query has been rewritten to speed it up and now runs sub 1 second.
> Bug: Optimise slow query breaking homepage

- api/reports/management/commands/reports.py
- api/reports/queries/standard.py
Allows reporting on cases/applications/licences based on their status and how
many of the 20 sla days have been used to process them
> LTD-478 MI Report: Cases by SLA

- api/flags/models.py
- api/workflow/routing_rules/models.py
This removes username from RoutingRule natural key as these will probably not be
consistent across environments.
Updates FlaggingRule natural key to support updated model
> Hotfix for exporting config

- api/reports/queries/standard.py
- use per team SLA days from new CaseAssignmentSLA
- include more end user details
> LTD-714 additional fields

- api/letter_templates/context_generator.py
- api/letter_templates/templates/letter_templates/nlr.html
- api/letter_templates/tests/tests_context_generation.py
> NLR template

- api/applications/creators.py
- api/applications/serializers/generic_application.py
- api/goods/tests/test_submitting_goods.py
Declaration validation criteria is updated.
Expose agreed_to_foi in the serializer as we display the details to case officer.
> LTD-625: Update validation when declaration is submitted

- api/applications/views/applications.py
- api/cases/views/views.py
Stopping notify emails for unapproved templates application_status (b9c3403a-8d09-416e-acd3-99baabf5b043) and ecju_query (bcf052e0-54d9-4ed2-b77e-2f5a77589466)
> LTD-880: Notify - some notifications to be turned off / deleted

- api/cases/tests/test_grant_licence.py
@agalamatis has confirmed that we do not send these emails rn so it is ok to remove the asserts for the same.
> Remove send_email check and xfail.

- api/cases/tests/test_create_final_advice.py
- api/cases/tests/test_team_advice.py
I fixed one failing test and deleted the others because these tests are 2y old, we are not sure what they are trying to tell us & the current logic in the code doesn't agree with the tests.
> [LTD-903] Advice tests failing

- api/flags/tests/test_list_flags.py
- api/flags/views.py
- docs/flags.md
This PR adds a technical document and fixes a bug that was exposed while writing this document.
> [LTD-1011] System Flags

- api/data_workspace/good_views.py
- api/data_workspace/license_views.py
- api/data_workspace/staticdata_views.py
- api/data_workspace/tests/test_good_views.py
- api/data_workspace/tests/test_license_views.py
- api/data_workspace/tests/test_staticdata_views.py
- api/data_workspace/tests/test_views.py
- api/data_workspace/urls.py
- api/data_workspace/views.py
- api/parties/serializers.py
This adds the remaining endpoints required for `LTD-1025`.
I reckon it would be best to review commit-wise.
> LTD-1025: Add remaining endpoints

- api/applications/serializers/generic_application.py
- api/applications/serializers/good.py
- api/applications/tests/test_application_status.py
- api/applications/tests/test_goods_type_on_application.py
- api/compliance/tests/test_exporter_compliance_views.py
- api/data_workspace/application_views.py
- api/data_workspace/good_views.py
- api/data_workspace/tests/test_application_views.py
- api/data_workspace/tests/test_good_views.py
- api/data_workspace/tests/test_staticdata_views.py
- api/data_workspace/urls.py
- api/goods/serializers.py
- api/goods/tests/test_create.py
- api/goods/tests/test_edit.py
- api/staticdata/control_list_entries/serializers.py
Add missing endpoint to expose `GoodOnApplicationControlListEntry` and `GoodControlListEntry` models to DW
Add additional fields to serializer to support reporting pipelines
> LTD-1025: Add missing endpoint and extend serializer fields

- api/cases/tasks.py
- api/cases/tests/test_sla.py
Ensure that we don't double count the department SLA where a case is assigned to multiple teams from the same department.
> Don't double-count department SLA days

- api/data_workspace/license_views.py
- api/data_workspace/tests/test_license_views.py
- api/licences/serializers/view_licence.py
id and Licence_id were missing
> LTD-994: Add more fields to GoodOnLicences serializer for reports

- api/data_workspace/license_views.py
- api/data_workspace/serializers.py
- api/data_workspace/tests/test_serializers.py
Goods are not required by the LITELicencesPipeline, so don't serialize them.
> Don't serialize nested goods

- api/cases/libraries/get_case.py
- api/cases/views/views.py
Approximate 40% reduction in number of SQL queries when serializing a `Case`.
> Reduce number of SQL queries when retrieving a Case

- api/licences/helpers.py
- api/licences/tests/test_get_licences.py
This reverts commit d2a80ad36cb25bdc0e079b2f39e7c0b0b559ac38, reversing
changes made to cc232ed8bf8a63d7c4b52b9c025095404817a112.
> Revert "Merge pull request #875 from uktrade/LTD-1528-fix-nlr-missing-advice…"

- api/letter_templates/templates/letter_templates/ecju_base.html
- api/letter_templates/templates/letter_templates/siel.html
changing content for letter templates as in LTD-1378
> changing content for letter templates as in LTD-1378

- api/staticdata/countries/migrations/0003_add_nir.py
- api/staticdata/countries/test.py
Enable Northern Ireland to the country list.
SS After:
> LTD-1888-Export-GB-NIR

- api/applications/models.py
- api/applications/serializers/standard_application.py
- api/applications/serializers/temporary_export_details.py
- api/applications/views/temporary_export_details.py
> Fix locations issues ltd 1891

- api/applications/enums.py
- api/applications/serializers/standard_application.py
- api/applications/serializers/temporary_export_details.py
fixing Locations issues by making the whole journey into single lite forms group. Issues as shown in LTD-1891 and more.
> fixing locations issues

- api/applications/creators.py
When exporter is ready to submit we perform various validations to check
whether all the required details are captured or not.
One such validation is to check whether Party related documents are
uploaded or not. Current validation assumes each party only uploads
one document but with English translation and letterhead changes an
End-user may upload upto 3 documents so update the validation to
take this into account.
> LTD-1368: Update Party document validation during application submission

- .gitignore
- api/applications/libraries/get_applications.py
- api/cases/libraries/get_case.py
- api/cases/views/views.py
- api/goods/serializers.py
This optimises the performance of the `CaseDetail` endpoint by utilising `select_related` and `prefetch_related` where possible.
This is only the beginning of finding all the cases where we can optimise in this manner but we are stopping here for now.
> Ltd 1731 advice performance optimisations

- api/open_general_licences/serializers.py
Updated submodule for countries.
> LTD-2111 Fix GB resets on dev env

- api/applications/views/applications.py
LTD-2165 fixing missing serial number API filter
> LTD-2165 fixing missing serial number api filter

- api/applications/tests/test_finalise_application.py
- api/cases/libraries/reference_code.py
- api/cases/tests/test_reference_code.py
- api/licences/helpers.py
- api/licences/tests/test_get_licence_reference_code.py
- api/licences/tests/test_register_open_general_licence.py
- api/open_general_licences/tests/test_gets.py
reverting reference code changes from https://github.com/uktrade/lite-api/pull/915
> LTD-2222 reverting reference code changes

- api/cases/tests/test_good_precedents_view.py
- api/cases/urls.py
- api/cases/views/views.py
- api/goods/serializers.py
This adds an endpoint that exposes precedents.
Precedents are defined as `GoodOnApplication` that share the same `Good` but are associated with an application that has already been submitted.
> [LTD-2174] Precedent

- api/letter_templates/tests/test_create.py
- api/letter_templates/tests/test_view.py
- api/staticdata/management/commands/seedall.py
- api/staticdata/management/commands/seedroutingrules.py
Add management command to seed routing rules for UI tests.
> LTD-2228: Add command to seed routing rules

- Dockerfile.db
- docker-compose.e2e.yml
- start-e2e.sh
Rather than attempt to create data fixtures to simulate UAT/Prod like environments we will now be dumping UAT DB to exercise the UI tests
> Remove e2e seed step in favour of db dump

- api/external_data/management/commands/ingest_ui_test_sanctions.py
- start-e2e.sh
prefill ES in order for tests based on it will work during CI
> prefill ES in order for tests based on it will work during CI

- api/applications/tests/test_application_status.py
- api/applications/views/applications.py
- api/audit_trail/formatters.py
- api/audit_trail/tests/test_audit_payload.py
> LTD-2407 Content changes

- cloudbuild-release.yaml
Tagging api image during release with correct release version
> new cloud build file release GCR trigger

- .circleci/config.yml
- api/core/celery_tasks.py
- gov_notify/service.py
- gov_notify/tests/test_service.py
integrate celery and notifications
> integrate celery and notifications

- api/applications/tests/factories.py
Reference need to be unique so use real faker to regenerate it every time factory is instantiated.
> Use real faker to generate random reference for Denial factory

- api/goods/serializers.py
- api/goods/tests/test_edit.py
adding missing software product fields
> adding missing software product fields

- test_helpers/clients.py
This will assist in the BDD tests for C5 MTCR routing.
> Make test client create application method more configurable

- api/goods/serializers.py
fixing security details going blank while editing
> fixing security details going blank while editing

- api/users/tests/test_view.py
- api/users/views.py
If not excluded user can select when he logs in and fails
> LTD-2962: Exclude rejected organisations from the list of user organisations

- api/applications/views/applications.py
- test_helpers/clients.py
There's a feature flag in the UI which sets check_ security_approvals this is used in API and if switched off it removes any validation error messages. This feature flag is being removed in the UI will post PR
> LTD-2997-remove-f680-ff

- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
Introduce a filter for cases with a nsg list type of "TRIGGER_LIST"
<del>includes commits from #1224  so waiting for that to be merged first.</del>
> Add trigger list to advanced filters

- api/applications/serializers/good.py
- api/data_workspace/application_views.py
- api/data_workspace/staticdata_views.py
- api/data_workspace/tests/test_application_views.py
- api/data_workspace/tests/test_staticdata_views.py
- api/data_workspace/urls.py
- api/staticdata/regimes/serializers.py
We need to generate a report of products related to trigger list. These fields are recently added to our data model and not available in DW.
Add endpoints and make them available for DW to pull this data.
> LTD-3054: Export trigger list data fields to DW

- api/applications/tests/factories.py
- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
- api/goods/tests/factories.py
- api/staticdata/regimes/helpers.py
- api/staticdata/regimes/tests/test_helpers.py
- api/staticdata/regimes/tests/test_views.py
- api/staticdata/regimes/urls.py
- api/staticdata/regimes/views.py
As per LTD-3121, this PR add option within advanced search on internal site
> adding regime entry search to advanced search on internal site

- Dockerfile.e2e
Assume submodules are present on host before Dockerfile.e2e build step.
> LTD-3293 Adjust Dockerfile.e2e

- manifest.yml
> pin-python-build-pack-to-1.8.3

- api/applications/helpers.py
- api/applications/tests/test_finalise_application.py
Cases are sometimes sent back to update product assessment. If we try to finalise them without consolidating the advice again then previously added products will still remain on the licence. This can be an issue if they have become NLR after product assessment changes. Identify this case and exclude any NLR items when finalising the application.
> LTD-3303: Ensure products on licence are correctly updated after product assessment changes

- api/applications/helpers.py
- api/applications/tests/test_finalise_application.py
Cases are sometimes sent back to update product assessment. If we try to finalise them without consolidating the advice again then previously added products will still remain on the licence. This can be an issue if they have become NLR after product assessment changes. Identify this case and exclude any NLR items when finalising the application.
> Ensure products on licence are correctly updated after product assessment changes

- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
We have changed the options for trigger list assessment and introduced a new field to save that data. We also have a filter that needs to be updated to filter the cases correctly.
> LTD-3331: Update trigger list filter to use correct field

- api/workflow/user_queue_assignment.py
- This is now moved to lite-routing hence replace with that function. This is to make it easier to update it with changes for countersigning flow and be able to test it through all combinations
- Update sha
> LTD-3358: Replace Case moving forward code with refactored function

- api/applications/notify.py
- api/applications/tests/test_notify.py
- gov_notify/enums.py
- gov_notify/payloads.py
- gov_notify/tests/test_enums.py
- test_helpers/clients.py
take application and send email notification to caseworker that needs to act on the comments
notify template: https://www.notifications.service.gov.uk/services/f3d8fb42-a34b-4d85-8ac2-a62006a197dc/templates/4d418015-cd7c-498f-a972-72e7ec4468cc
> email notification for cases sent back by countersign

- Pipfile
- Pipfile.lock
Update Pipfile to install `django-test-migrations = "~=1.2.0"`
> Add Django test migrations package for testing migrations

- api/users/tests/test_exporter_authentication.py
- api/users/views.py
Fixes an issue where the users first and last name and pending status weren't being set correctly and was causing UI tests to fail.
> LTD-3419-Revert-bug

- api/cases/tests/test_case_search.py
This fixes the case search API endpoint test by ensuring that it uses a timezone aware date object and expects the resulting field to be rendered in the way rest framework would render it.
> Fix case search API test following timezone change

- api/applications/libraries/case_status_helpers.py
- api/applications/tests/test_application_status.py
- api/staticdata/statuses/enums.py
- api/staticdata/statuses/libraries/get_case_status.py
- api/workflow/tests/test_flagging_rules.py
- Also update use of choices in remaining places
[LTD-3535](https://uktrade.atlassian.net/browse/LTD-3535)
[LTD-3535]: https://uktrade.atlassian.net/browse/LTD-3535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-3535: Capitalize first letter for Countersign statuses

- api/applications/tests/test_finalise_application.py
- update countersigning flag name and fixes failing tests
> Update lite-routing sha

- api/cases/managers.py
- api/cases/tests/test_case_search.py
The 'flags' filter doesn't consider flags related to parties hence not showing any Cases when filtered by any of these flags.
> LTD-3589: Consider Party flags when filtering Cases

- api/audit_trail/managers.py
- api/audit_trail/service.py
- api/audit_trail/tests/test_audit_trail.py
- api/cases/serializers.py
- api/cases/service.py
- api/cases/tests/test_get_case.py
- api/cases/views/search/service.py
> Staging release

- api/audit_trail/payload.py
[LTD-3693](https://uktrade.atlassian.net/browse/LTD-3693)
[LTD-3693]: https://uktrade.atlassian.net/browse/LTD-3693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-3693-Mentions-content

- api/cases/tests/test_case_notes.py
- api/cases/views/case_notes.py
Add pagination to user-case-mentions
https://uktrade.atlassian.net/browse/LTD-3695
>  LTD-3695-usercase-mentions-pagination 

- Pipfile.lock
> Update lock file

- Pipfile.lock
> Fix pip lock

- api/goods/tests/test_control_codes.py
- api/goods/views.py
removed current_object and changed the goodonapplication query to point at good.id, the frontend changes reflect this also
[LTD-3290](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3290)
[LTD-3290]: https://uktrade.atlassian.net/browse/LTD-3290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-3290 Timeout on TAU product assessment

- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
- api/cases/views/search/views.py
- api/staticdata/regimes/views.py
Add multi-select functionality to regime and CLE filters.
[LTD-3828](https://uktrade.atlassian.net/browse/LTD-3828)
[LTD-3829](https://uktrade.atlassian.net/browse/LTD-3829)
[LTD-3828]: https://uktrade.atlassian.net/browse/LTD-3828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-3829]: https://uktrade.atlassian.net/browse/LTD-3829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regime and CLE multi-select for Product filter tab

- api/cases/managers.py
- api/cases/tests/test_case_search_advanced.py
- api/cases/views/search/views.py
Support exclude CLE / regime case searches
[LTD-3853](https://uktrade.atlassian.net/browse/LTD-3853)
[LTD-3858](https://uktrade.atlassian.net/browse/LTD-3858)
[LTD-3853]: https://uktrade.atlassian.net/browse/LTD-3853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-3858]: https://uktrade.atlassian.net/browse/LTD-3858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Exclude cle/regime functionality added to the case search

- api/cases/managers.py
- api/cases/tests/test_case_search.py
- api/cases/views/search/views.py
> LTD-3959-filtering

- api/cases/generated_documents/tests/test_generate_document.py
- api/letter_templates/constants.py
- api/letter_templates/helpers.py
- api/letter_templates/templates/letter_templates/application_form.html
- api/letter_templates/templates/letter_templates/nlr.html
- api/letter_templates/templates/letter_templates/pdf_generation_base.html
- api/letter_templates/templates/letter_templates/refusal.html
- api/letter_templates/templates/letter_templates/siel.html
This is a small refactoring for generating PDFs.
> Ltd 3993 embed hyperlinks

- api/applications/serializers/advice.py
https://uktrade.atlassian.net/browse/LTD-3965
> LTD-3965-update-serializer-note

- api/appeals/factories.py
- api/appeals/serializers.py
- api/appeals/tests/factories.py
- api/appeals/tests/test_models.py
- api/appeals/tests/test_views.py
- api/appeals/urls.py
- api/appeals/views.py
- api/applications/serializers/standard_application.py
- api/applications/tests/test_appeal.py
Adds an endpoint to get the details of an appeal document.
Adds appeal to the standard application serializer.
[LTD-4126](https://uktrade.atlassian.net/browse/LTD-4126)
> Ltd 4126 appeal details

- api/staticdata/denial_reasons/migrations/0004_denial_reasons_update.py
- api/staticdata/denial_reasons/migrations/tests/test_0004_denial_reasons_update.py
https://uktrade.atlassian.net/browse/LTD-3995
Depends on this to have test passed:
https://github.com/uktrade/lite-content/pull/305
> LTD-3995-DR-migration

- api/applications/tests/test_view_application.py
- api/applications/views/applications.py
- api/cases/generated_documents/helpers.py
- api/cases/generated_documents/tests/test_generate_document.py
- api/cases/generated_documents/views.py
- api/queries/end_user_advisories/views.py
- api/staticdata/upload_document_for_tests/views.py
- api/users/tests/test_exporter_user_notifications.py
Replace exception message with generic error messages to avoid exposing internal details
[LTD-4197](https://uktrade.atlassian.net/browse/LTD-4197)
[LTD-4197]: https://uktrade.atlassian.net/browse/LTD-4197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4197: Fix CodeQL warnings

- api/applications/views/applications.py
- api/cases/notify.py
- api/cases/tests/test_notify.py
- gov_notify/enums.py
- gov_notify/payloads.py
On submission of an appeal we send an acknowledgement to Exporter that it has been received.
Template is created in Notify.
[LTD-4220](https://uktrade.atlassian.net/browse/LTD-4220)
[LTD-4220]: https://uktrade.atlassian.net/browse/LTD-4220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4220: Notify Exporter when an appeal is submitted

- .circleci/config.yml
- api/search/product/documents.py
- api/search/product/tests/test_views.py
- api/search/product/views.py
Update the document defined to index product data (GoodOnApplication) to improve the relevance of search results.
Explicitly specify the fields to be searched.
[LTD-4296](https://uktrade.atlassian.net/browse/LTD-4296)
[LTD-4296]: https://uktrade.atlassian.net/browse/LTD-4296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4296: Improve relevance of Product search results

- api/search/product/documents.py
- api/search/product/serializers.py
- api/search/product/tests/test_views.py
- api/search/product/views.py
Update Product document to index assessing officer details and assessment date.
Order results based on assessment_date.
[LTD-4340](https://uktrade.atlassian.net/browse/LTD-4340)
[LTD-4340]: https://uktrade.atlassian.net/browse/LTD-4340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4340: Index assessing officer and assessment date fields

- Dockerfile.e2e
- start-e2e.sh
> Match cf linux in docker e2e

- api/external_data/documents.py
updated address to use the address_analyzer and added suite to the stopwords
[LTD-4385](https://uktrade.atlassian.net/browse/LTD-4385)
[LTD-4385]: https://uktrade.atlassian.net/browse/LTD-4385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4385 add stopwords to address denialdocument

- api/search/product/serializers.py
- api/search/product/tests/test_views.py
Add a test to ensure fields in document match with serializer
[LTD-4405](https://uktrade.atlassian.net/browse/LTD-4405)
[LTD-4405]: https://uktrade.atlassian.net/browse/LTD-4405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-4405: Update field name in serializer to match with document

- api/external_data/tests/denial_valid.csv
- api/external_data/tests/test_views.py
additional tests for ES return values and testing the filter in unittests
[LTD-](https://uktrade.atlassian.net/browse/LTD-4419)
> Ltd 4419 denial search tests

- README.md
- makefile
No ticket - just cleaning up a couple of things in lite-api README and makefile.
> Update readme and makefile

- manifest.yml
This to increase double the mem on our webservers as we are now near the 1GB limit when multiple users are on the server. 
https://uktrade.atlassian.net/browse/LTD-4522
> LTD-4522-increase-mem-webserver

- api/search/product/tests/test_views.py
Sometimes the order of suggestions returned is different so update the test to sort the results and compare.
> Update suggestions to test to use sorted variables

- api/cases/celery_tasks.py
- api/documents/celery_tasks.py
- api/external_data/celery_tasks.py
- api/licences/celery_tasks.py
Use celery logger utility for celery tasks.  This injects the celery task ID in to the log line.
[LTD-4608](https://uktrade.atlassian.net/browse/LTD-4608)
[LTD-4608]: https://uktrade.atlassian.net/browse/LTD-4608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use celery log util

- api/conf/settings.py
https://uktrade.atlassian.net/browse/LTD-4597
> LTD-4597-celery-healthcheck

- api/cases/notify.py
- api/cases/tests/test_case_ecju_queries.py
- gov_notify/payloads.py
Add open days as a parameter to email
> LTD-4700-working-add-open-days-template 

- api/data_workspace/serializers.py
- api/data_workspace/tests/test_views.py
- api/data_workspace/urls.py
- api/data_workspace/views.py
- api/survey/models.py
https://uktrade.atlassian.net/browse/LTD-4671
> LTD-4671-hcsat-dw

- .circleci/.github/CODEOWNERS
https://uktrade.atlassian.net/browse/LTD-4794
>  LTD-4794-add-code-owners 

- api/applications/permissions.py
- api/applications/tests/test_permissions.py
- api/applications/urls.py
- api/applications/views/party_documents.py
- api/applications/views/tests/test_party_documents.py
- api/parties/tests/factories.py
Add endpoint for streaming party documents from S3.
[LTD-4688](https://uktrade.atlassian.net/browse/LTD-4688)
[LTD-4688]: https://uktrade.atlassian.net/browse/LTD-4688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-4688] Add party document streaming endpoint

- api/organisations/views/documents.py
Fix an issue where HAWK authentication hash checks fail when responding with a blank dict in a JSON response.
[LTD-4688](https://uktrade.atlassian.net/browse/LTD-4688)
[LTD-4688]: https://uktrade.atlassian.net/browse/LTD-4688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 4688 fix deleting document on organisation

- api/document_data/health_checks.py
- api/document_data/tests/test_health_checks.py
Ignore files that were generated as the backup was taking place
[LTD-4836](https://uktrade.atlassian.net/browse/LTD-4836)
[LTD-4836]: https://uktrade.atlassian.net/browse/LTD-4836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ignore files that were generated as the backup was taking place

- api/letter_templates/templates/letter_templates/nlr.html
Change 'Her Majesty' to 'His Majesty'
[LTD-4850](https://uktrade.atlassian.net/browse/LTD-4850)
[LTD-4850]: https://uktrade.atlassian.net/browse/LTD-4850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change 'Her Majesty' to 'His Majesty'

- api/applications/tests/factories.py
Add a lightweight F680ApplicationFactory class so we can quickly create dummy applications.
> Add simple F680ApplicationFactory

- api/applications/creators.py
> F680 submit validation

- api/applications/tests/factories.py
Update f680 factory to add an end user
> Update f680 factory to add an end user

- api/workflow/user_queue_assignment.py
Ensure F680 cases skip MOD countersigning.
> Ensure F680 cases skip MOD countersign

- api/applications/libraries/case_status_helpers.py
- api/applications/libraries/get_applications.py
- api/applications/managers.py
- api/applications/models.py
- api/applications/serializers/open_application.py
- api/applications/tests/factories.py
- api/applications/views/applications.py
Ensure that canned products are created for crypto OIELs on submission.
Additionally, flesh out API endpoints to ensure that crypto OIELs can be viewed on caseworker application.
> [Cytpo-OIELs] Crypto OIEL canned products

- .circleci/config.yml
Fix E2E circleci job for crypto oiels.
> Fix circleci E2E tests by pointing to more permanent branch

- api/external_data/serializers.py
- api/external_data/tests/test_views.py
This is to prevent any XSS possible attacks by making safe the fields loaded from CSV
> LTD-4997-sanitise-csv-upload 

- api/external_data/serializers.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
https://uktrade.atlassian.net/browse/LTD-4993 
Adds Party Denial Details on the screen together with ability to highlight. Highlight is depended on FE change as well. 
https://github.com/uktrade/lite-frontend/pull/1935
> add highlighting

- api/document_data/health_checks.py
- api/document_data/tests/test_health_checks.py
Handle shift to BST when running backup document healthcheck
[LTD-4901](https://uktrade.atlassian.net/browse/LTD-4901)
[LTD-4901]: https://uktrade.atlassian.net/browse/LTD-4901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Handle shift to BST when running backup document healthcheck

- api/external_data/documents.py
- api/external_data/serializers.py
- api/external_data/tests/test_views.py
- api/external_data/views.py
Allow searching of denials based on regime ref
Corresponding front end  PR [here](https://github.com/uktrade/lite-frontend/pull/1987)
[LTD-5040](https://uktrade.atlassian.net/browse/LTD-5040)
[LTD-5040]: https://uktrade.atlassian.net/browse/LTD-5040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD 5040 allow searching on regime reg ref

- api/conf/pagination.py
- api/data_workspace/tests/test_application_views.py
- api/external_data/views.py
- api/goods/goods_paginator.py
- api/goods/views.py
https://uktrade.atlassian.net/browse/LTD-5067
> LTD-5067-increase-page-size-denial-search 

- api/cases/generated_documents/signing.py
- api/cases/generated_documents/tests/test_generate_document.py
https://uktrade.atlassian.net/browse/LTD-1667
> LTD-1667-PDF

- api/conf/settings.py
- api/goods/views.py
This is not giving any value and mostly noise now so remove it.
> Remove unnecessary warning

- api/cases/generated_documents/tests/test_generate_document.py
- api/letter_templates/templates/letter_templates/inform_letter.html
https://uktrade.atlassian.net/browse/LTD-5093
> LTD-5093-inform-letter

- api/applications/constants.py
- api/applications/creators.py
- api/applications/tests/test_standard_application_submit.py
Updates the error messages shown when a document fails to be processed.
[LTD-4996](https://uktrade.atlassian.net/browse/LTD-4996)
[LTD-4996]: https://uktrade.atlassian.net/browse/LTD-4996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improve file processing error messages

- api/applications/managers.py
- api/applications/serializers/generic_application.py
- api/applications/tests/test_view_application.py
- api/applications/views/applications.py
https://uktrade.atlassian.net/browse/LTD-5066
https://uktrade.atlassian.net/browse/LTD-5065
> LTD-5066-5065-content

- .circleci/config.yml
- api/assessments/tests/test_views.py
- api/goods/tests/test_submitting_goods.py
- api/goods/views.py
> LTD: Good cannot be edited if it is already submitted on an application

- api/licences/models.py
- api/licences/serializers/view_licence.py
- api/licences/tests/test_get_licences.py
This goes together with the new view to update licence details 
https://github.com/uktrade/lite-frontend/pull/2089/files
case_status is required to ensure we can edit the licence as this is part of the permission check. 
https://uktrade.atlassian.net/browse/LTD-5242
> LTD-5242-add-change-status-view-API-change

- api/applications/views/tests/test_parties.py
- api/parties/models.py
- api/parties/tests/test_models.py
[LTD-5306](https://uktrade.atlassian.net/browse/LTD-5306)
[LTD-5306]: https://uktrade.atlassian.net/browse/LTD-5306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5306 added reversion to parties

- api/applications/management/commands/update_good_name.py
- api/applications/tests/test_update_good_name.py
> same as previous commit but good name

- api/applications/management/commands/update_party_address.py
[LTD-5387](https://uktrade.atlassian.net/browse/LTD-5387)
[LTD-5387]: https://uktrade.atlassian.net/browse/LTD-5387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5387 fix \r\n issue

- api/core/tests/test_validators.py
- api/core/validators.py
- api/goods/serializers.py
- api/goods/tests/test_serializers.py
- api/parties/serializers.py
- api/parties/tests/test_serializers.py
[LTD-5383](https://uktrade.atlassian.net/browse/LTD-5383)
[LTD-5383]: https://uktrade.atlassian.net/browse/LTD-5383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ltd 5383 Good name and Party address validator

- api/letter_templates/migrations/0010_refusal_letter_picklist_update_team_ownership.py
- api/letter_templates/migrations/tests/test_0010_refusal_letter_picklist_update_team_ownership.py
- api/picklists/tests/test_views.py
https://uktrade.atlassian.net/browse/LTD-5435
The current ownership of this item is with Admin 
LU own this and need to be able to make changes.
> LTD-5435-change-refusal-letter-ownership 

- api/data_workspace/v1/serializers.py
- api/data_workspace/v1/tests/test_licence_views.py
- api/data_workspace/v1/tests/test_serializers.py
Fix the shape of the DW output to match what DW is expecting.
[LTD-5457](https://uktrade.atlassian.net/browse/LTD-5457)
[LTD-5457]: https://uktrade.atlassian.net/browse/LTD-5457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Correct the shape of the output for DW licences

- Pipfile
- Pipfile.lock
Move drf-spectacular into main requirements.
It was incorrect to add it to the dev requirements and this breaks building the app on deployment as a result.
[LTD-5533](https://uktrade.atlassian.net/browse/LTD-5533)
[LTD-5533]: https://uktrade.atlassian.net/browse/LTD-5533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move drf spectacular into main requirements

- api/letter_templates/templates/letter_templates/siel.html
- api/letter_templates/tests/test_letter_templates.py
Amend pdf licence to reflect applied for amount
[LTD-5541](https://uktrade.atlassian.net/browse/LTD-5541)
[LTD-5541]: https://uktrade.atlassian.net/browse/LTD-5541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5541-licence-to-reflect-quantity-applied-for

- api/applications/models.py
- api/assessments/serializers.py
- api/assessments/tests/test_views.py
- api/staticdata/report_summaries/migrations/0009_add_ars_subject_prefix_oct_2024.py
- api/staticdata/report_summaries/migrations/data/0009_add_report_summaries_oct_2024/report_summary_prefix.json
- api/staticdata/report_summaries/migrations/data/0009_add_report_summaries_oct_2024/report_summary_subject.json
- api/staticdata/report_summaries/migrations/tests/test_0009_add_ars_subject_prefix_oct_2024.py
This change adds a few new report summary subjects/prefixes.
[LTD-5586](https://uktrade.atlassian.net/browse/LTD-5586)
[LTD-5586]: https://uktrade.atlassian.net/browse/LTD-5586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5586] Add new report summary subject/prefixes

- api/cases/generated_documents/tests/factories.py
- api/cases/tests/test_finalise_advice.py
- api/cases/tests/test_grant_licence.py
- api/gov_users/tests/test_roles_and_permissions.py
- api/letter_templates/tests/factories.py
- api/teams/tests/test_list_user_by_team.py
- test_helpers/clients.py
Some of the setup code is repeated in each test.
Create specific users and factories to minimise repetition and make tests more consistent.
> LTD: Improvements to tests to use factories

- api/conf/settings_test.py
- api/data_workspace/metadata/routers.py
- api/data_workspace/metadata/tests/auto_field_urls.py
- api/data_workspace/metadata/tests/serializers.py
- api/data_workspace/metadata/tests/test_metadata.py
- api/data_workspace/metadata/tests/urls.py
- api/data_workspace/metadata/tests/views.py
- api/data_workspace/v2/serializers.py
- api/data_workspace/v2/urls.py
- api/data_workspace/v2/views.py
This provides an automated metadata endpoint for registering Data Workspace specific endpoints.
The aim of this is to dynamically generate the tables on the Data Workspace side with all of the configuration coming from LITE instead of duplicating the configuration in multiple places.
[LTD-5664](https://uktrade.atlassian.net/browse/LTD-5664)
[LTD-5664]: https://uktrade.atlassian.net/browse/LTD-5664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Automated metadata endpoint

- api/letter_templates/templates/letter_templates/refusal.html
- api/letter_templates/templates/letter_templates/siel.html
- api/letter_templates/templatetags/custom_tags.py
- api/letter_templates/tests/test_letter_templates.py
- assets/css/siel.css
- assets/css/siel_preview.css
In licence document pdf, added fixed-layout for all table elements.  Removed unnecessary template tag.  Testing info in comments on ticket.
[LTD-5722](https://uktrade.atlassian.net/browse/LTD-5722)
[LTD-5722]: https://uktrade.atlassian.net/browse/LTD-5722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5722 fix licence pdf css

- api/conf/settings.py
Update sanctions list to latest
https://uktrade.atlassian.net/browse/LTD-5762
https://assets.publishing.service.gov.uk/media/6776a7d49d03f12136308d1c/UK_Sanctions_List.xml
>  LTD-5762-update-uk-sanctions-list 

- api/applications/tests/factories.py
- api/cases/libraries/get_flags.py
- api/cases/tests/conftest.py
- api/cases/tests/test_case_flags.py
- api/cases/tests/test_helpers.py
- api/users/tests/factories.py
This ensures we see same set of flags on the queue view and case detail page.
[LTD-5775](https://uktrade.atlassian.net/browse/LTD-5775)
[LTD-5775]: https://uktrade.atlassian.net/browse/LTD-5775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-5775: Display all destinations flags on Case detail page

- api/applications/serializers/standard_application.py
Fix the shape of the case officer payload that is expected by data workspace.
[LTD-5874](https://uktrade.atlassian.net/browse/LTD-5874)
[LTD-5874]: https://uktrade.atlassian.net/browse/LTD-5874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix shape of case officer on DW endpoint

- api/applications/helpers.py
- api/applications/libraries/get_applications.py
- api/applications/libraries/tests/test_get_applications.py
- api/applications/managers.py
- api/applications/models.py
- api/cases/application_manifest.py
- api/cases/models.py
- api/cases/tests/test_application_manifest.py
- api/cases/tests/test_models.py
- api/f680/caseworker/serializers.py
- api/f680/managers.py
- api/f680/models.py
Ensure that caseworker case detail endpoint is compatible with returning F680 applications.
[LTD-5887](https://uktrade.atlassian.net/browse/LTD-5887)
[LTD-5887]: https://uktrade.atlassian.net/browse/LTD-5887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-5887] Ensure F680s can be viewed on caseworker app

- .circleci/config.yml
- .coveragerc
- scripts/tests/test_which_frontend_branch.py
- scripts/which_frontend_branch.py
> merge-back-hot-fix-inti-branch-selection 

- .circleci/config.yml
Store the test results for better display in CircleCI.
> Store output of test results

- api/cases/views/search/service.py
- api/teams/tests/factories.py
Remove unnecessary look for goods flags on search view.
> Remove unnecessary lookup of goods flags

- api/applications/exporter/views/tests/test_applications.py
Fix failing test because of clocks moving forward.
> LTD: Update test to ignore timezone changes

- api/f680/caseworker/permissions.py
All these teams to make recommendations on F680. 
One question that arises here is should we also confirm the case is in the relevant queue.
> fix-permissions-make-recommandations-f680-teams 

- api/letter_templates/caseworker/filters.py
- api/letter_templates/caseworker/tests/test_view.py
We can request templates for multiple decisions but current filter only accepts single value.
> LTD-6016: Update letter template decision filter to accept multiple values

- api/application_manifests/base.py
- api/applications/application_manifest.py
- api/cases/celery_tasks.py
- api/cases/models.py
- api/cases/notify.py
- api/cases/tests/test_case_ecju_queries.py
- api/cases/tests/test_notify.py
- api/f680/application_manifest.py
- gov_notify/enums.py
- gov_notify/payloads.py
Send alternative emails for F680s ECJU Queries
[LTD-6080](https://uktrade.atlassian.net/browse/LTD-6080)
[LTD-6080]: https://uktrade.atlassian.net/browse/LTD-6080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LTD-6080] F680 ECJU Query emails

- api/addresses/serializers.py
- api/addresses/tests/test_postcode_validation.py
may need to move it to frontend if we don't want to automate
[LTD-6126](https://uktrade.atlassian.net/browse/LTD-6126)
[LTD-6126]: https://uktrade.atlassian.net/browse/LTD-6126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6126 added postcode serialisation to upper and strip

- api/applications/tests/factories.py
- api/cases/libraries/get_flags.py
- api/cases/tests/libraries/test_get_flags.py
Update the flag logic so that it's the same for each application type.
[LTD-6179](https://uktrade.atlassian.net/browse/LTD-6179)
[LTD-6179]: https://uktrade.atlassian.net/browse/LTD-6179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make flag getting logic consistent across application types

- api/letter_templates/templates/letter_templates/f680_approval.html
- api/letter_templates/templates/letter_templates/f680_refusal.html
- assets/css/f680_approval.css
> LTD-6196: Outcome letter content changes

- api/application_manifests/base.py
- api/applications/application_manifest.py
- api/applications/caseworker/views/applications.py
- api/applications/exporter/views/applications.py
- api/applications/helpers.py
- api/applications/views/applications.py
- api/cases/serializers.py
- api/f680/application_manifest.py
- api/f680/exporter/serializers.py
- api/f680/exporter/tests/test_views.py
To use the exporter serializer for the exporter summary page and to fix the status field that was not correctly being added to the serializer.
[LTD-6201](https://uktrade.atlassian.net/browse/LTD-6201)
[LTD-6201]: https://uktrade.atlassian.net/browse/LTD-6201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6201 - Fix Application Detail incorrect serializer

- api/applications/serializers/standard_application.py
- api/f680/exporter/serializers.py
- api/queries/end_user_advisories/serializers.py
- api/users/serializers.py
To add exporter user notifications for F680s
[LTD-6113](https://uktrade.atlassian.net/browse/LTD-6113)
[LTD-6113]: https://uktrade.atlassian.net/browse/LTD-6113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6113 - User notifications

- api/f680/exporter/serializers.py
- api/f680/exporter/tests/test_views.py
Fix key error when trying to edit an f680
[LTD-6213](https://uktrade.atlassian.net/browse/LTD-6213)
[LTD-6213]: https://uktrade.atlassian.net/browse/LTD-6213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6213 - Fix F680 amend by copy

- api/f680/application_manifest.py
- api/letter_templates/templates/letter_templates/f680_ecju_mod_letter_base.html
Adjust address in F680 outcome letter template and adjust digital signature
[LTD-6207](https://uktrade.atlassian.net/browse/LTD-6207)
[LTD-6207]: https://uktrade.atlassian.net/browse/LTD-6207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6207 change address heading and digital signature

- api/f680/caseworker/filters.py
- api/f680/caseworker/mixins.py
- api/f680/caseworker/permissions.py
- api/f680/caseworker/tests/test_views.py
- api/f680/caseworker/urls.py
- api/f680/caseworker/views.py
There is some reusable functionality in the F680s recommendation/outcome views so this has been pulled out into a mixin and I've also used a backend filter so that only F680 cases are filtered and `get_queryset` to generate 404 when no case is found.
[LTD-6085](https://uktrade.atlassian.net/browse/LTD-6085)
[LTD-6085]: https://uktrade.atlassian.net/browse/LTD-6085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LTD-6085 Review lite-api caseworker view dispatch methods
